const BB610 = (() => {
  const LS={cart:'bb610_market_cart_v2',fav:'bb610_market_fav',compare:'bb610_market_compare'};
  const C=()=>BB610_DATA_SOURCE.catalog();
  const money=n=>n!==null&&n!==undefined&&Number.isFinite(Number(n))?new Intl.NumberFormat('uk-UA').format(Number(n))+' грн':'Ціна уточнюється';
  const get=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}};
  const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const rawProducts=()=>BB610_DATA_SOURCE.products();
  const sku=id=>BB610_DATA_SOURCE.sku(id);
  const defaultSku=id=>BB610_DATA_SOURCE.defaultSku(id);
  const view=p=>{const s=defaultSku(p.id);return {...p,name:p.name,officialName:p.official_name,category:p.category_id,categoryLabel:C().categories.find(c=>c.id===p.category_id)?.short_name||p.category_id,manufacturer:p.manufacturer,country:p.country,npk:p.npk,activeIngredient:p.active_ingredient,composition:p.composition||[],cultures:p.cultures||[],purposes:p.purposes||[],manufacturerUse:p.manufacturer_use,application:p.application,rate:p.rate,restrictions:p.restrictions,target:p.target,waitingPeriod:p.waiting_period,hazardClass:p.hazard_class,registration:p.registration,factoryPacks:p.factory_packs||[],documents:p.documents||[],instruction:(p.documents&&p.documents[0]?.title)||'Офіційне джерело виробника',source:p.source?.title||'',sourceUrl:p.source?.url||'',verifiedAt:p.verification?.verifiedAt||'',verified:!!p.verification?.verified,image:s?.image||p.image?.local||'',gallery:p.gallery||[],sku:s?.id||null,pack:s?.variant||'Фасовка BB610 уточнюється',price:s?.price??null,currency:s?.currency||'UAH',unit:s?.volume_weight?.unit||'шт',unitQty:s?.volume_weight?.value||1,stockStatus:s?.availability||'unknown',stockLabel:s?.stock_label||'Наявність уточнюється',shipping:s?.shipping||['Відправка по Україні — умови уточнюються'],supplier:s?.supplier||'Уточнюється',importer:s?.importer||'Уточнюється',packer:s?.packer||'Уточнюється',sizes:BB610_DATA_SOURCE.skusForProduct(p.id).map(x=>({id:x.id,label:x.variant,price:x.price,qty:x.volume_weight?.value,unit:x.volume_weight?.unit,status:x.offer_status,commercialStatus:x.commercial_status||'not-configured',stockLabel:x.stock_label||'Наявність уточнюється',availability:x.availability||'unknown',packSourceStatus:x.pack_source_status||'unknown'}))}};
  const products=()=>rawProducts().map(view);
  const byId=id=>{const p=BB610_DATA_SOURCE.product(id);if(p)return view(p);const s=sku(id);return s?view(BB610_DATA_SOURCE.product(s.product_id)):null};
  function commerceItem(s,quantity=1){if(!s)return null;const p=BB610_DATA_SOURCE.product(s.product_id);const item={item_id:s.id,item_name:p.name,item_brand:p.brand,item_category:C().categories.find(c=>c.id===p.category_id)?.name||p.category_id,item_variant:s.variant,quantity:Number(quantity)||1,currency:s.currency||'UAH'};if(s.price!==null&&s.price!==undefined)item.price=Number(s.price);return item}
  function pushEvent(event,payload={}){if(window.BB610Analytics?.push)return window.BB610Analytics.push(event,payload);window.dataLayer=window.dataLayer||[];if(payload.ecommerce)window.dataLayer.push({ecommerce:null});const data={event,...payload};window.dataLayer.push(data);document.dispatchEvent(new CustomEvent('bb610:ecommerce',{detail:data}));return null;}
  function trackList(list,listId='catalog',listName='Каталог'){const items=list.map((p,i)=>{const s=defaultSku(p.id);return s?{...commerceItem(s,1),index:i+1,item_list_id:listId,item_list_name:listName}:null}).filter(Boolean);if(items.length)pushEvent('view_item_list',{ecommerce:{item_list_id:listId,item_list_name:listName,items}})}
  function trackSelect(productId,listId='catalog',listName='Каталог'){const s=defaultSku(productId);if(s)pushEvent('select_item',{ecommerce:{item_list_id:listId,item_list_name:listName,items:[commerceItem(s,1)]}})}
  function unitPrice(p,price=p.price,qty=p.unitQty){if(price==null||!Number.isFinite(Number(price))||!qty)return '';const val=Number(price)/qty;return `${money(Math.round(val))} / ${p.unit}`}
  function addCart(id,qty=1){let s=sku(id);if(!s){const p=BB610_DATA_SOURCE.product(id);s=p?defaultSku(p.id):null}if(!s){toast('Фасовка BB610 ще не визначена');return false}const cart=get(LS.cart,[]);const row=cart.find(x=>x.sku===s.id);if(row)row.qty+=qty;else cart.push({sku:s.id,qty});set(LS.cart,cart);updateBadges();pushEvent('add_to_cart',{ecommerce:{currency:s.currency||'UAH',items:[commerceItem(s,qty)]}});toast('Додано до кошика');return true}
  function toggleArray(key,id,max){let arr=get(key,[]);arr=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];if(max&&arr.length>max){toast(`Максимум ${max} товари`);return false}set(key,arr);updateBadges();updateCompareBar();return arr.includes(id)}
  const toggleFav=id=>toggleArray(LS.fav,id); const toggleCompare=id=>toggleArray(LS.compare,id,4);
  function updateBadges(){const cart=get(LS.cart,[]).reduce((s,x)=>s+x.qty,0),fav=get(LS.fav,[]).length,cmp=get(LS.compare,[]).length;document.querySelectorAll('[data-count=cart]').forEach(e=>e.textContent=cart);document.querySelectorAll('[data-count=fav]').forEach(e=>e.textContent=fav);document.querySelectorAll('[data-count=compare]').forEach(e=>e.textContent=cmp)}
  function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';Object.assign(t.style,{position:'fixed',right:'18px',bottom:'18px',background:'#f0b24c',color:'#111',padding:'12px 16px',borderRadius:'10px',fontWeight:'800',zIndex:100,boxShadow:'0 10px 30px #0008'});document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',1800)}
  function productUrl(p){const slug=p.slug||p.id;if(p.runtime_dynamic)return `product.html?id=${encodeURIComponent(p.id)}`;return location.protocol==='file:'?`products/${slug}/index.html`:(p.canonical_product_url||`/products/${slug}/`)}
  function cardV2(p){const fav=get(LS.fav,[]).includes(p.id),cmp=get(LS.compare,[]).includes(p.id),s=defaultSku(p.id);const keyMeta=s?.variant||(p.npk&&p.npk!=='—'?`NPK ${p.npk}`:(p.form||p.categoryLabel||''));return `<article class="product-card product-card-v2" data-product-id="${p.id}"><a class="product-media" href="${productUrl(p)}" data-select-product="${p.id}"><img loading="lazy" src="${p.image}" alt="${p.name}"><div class="product-tags">${p.verified?'<span class="tag verified-tag">BB610 VERIFIED</span>':''}</div></a><div class="product-body"><div class="product-brand">${p.brand}</div><a class="product-name" href="${productUrl(p)}" data-select-product="${p.id}">${p.name}</a><div class="product-spec">${keyMeta}</div><div class="stock">${p.stockLabel}</div><div class="price-row"><div><div class="price">${money(p.price)}</div><div class="unit-price">${unitPrice(p)||'Комерційні параметри BB610 ще не визначені'}</div></div></div><div class="card-actions"><button class="btn buy-btn" data-add="${s?.id||p.id}">КУПИТИ</button><button class="btn ghost fav-toggle" data-fav="${p.id}">${fav?'♥':'♡'}</button><button class="btn ghost compare-toggle" data-compare="${p.id}">${cmp?'✓':'⇄'}</button></div></div></article>`}
  const card=cardV2;
  function bindCards(scope=document){scope.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));scope.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const on=toggleFav(b.dataset.fav);b.textContent=on?'♥':'♡'});scope.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const on=toggleCompare(b.dataset.compare);if(on!==false)b.textContent=on?'✓':'⇄'});scope.querySelectorAll('[data-select-product]').forEach(a=>a.addEventListener('click',()=>trackSelect(a.dataset.selectProduct,a.closest('#home-products')?'home-popular':'catalog',a.closest('#home-products')?'Популярні товари':'Каталог')))}
  function updateCompareBar(){const arr=get(LS.compare,[]),bar=document.querySelector('.compare-bar');if(!bar)return;bar.classList.toggle('show',arr.length>0);bar.querySelector('[data-compare-bar-count]').textContent=arr.length}
  function searchSubmit(form){const q=form.querySelector('input').value.trim();pushEvent('search',{search_term:q});location.href='catalog.html?q='+encodeURIComponent(q);return false}
  function renderCategoryNav(){document.querySelectorAll('.nav .container').forEach(nav=>{const catLinks=[...nav.querySelectorAll('a[href*="category="]')];if(!catLinks.length)return;const first=catLinks[0];C().categories.filter(c=>c.enabled).sort((a,b)=>a.order-b.order).forEach((c,i)=>{let a=catLinks[i];if(!a){a=document.createElement('a');first.parentNode.insertBefore(a,catLinks[catLinks.length-1]?.nextSibling||null)}a.href='catalog.html?category='+encodeURIComponent(c.id);a.textContent=c.short_name||c.name});catLinks.slice(C().categories.filter(c=>c.enabled).length).forEach(a=>a.remove())})}
  function migrateLegacyCart(){if(localStorage.getItem(LS.cart))return;const legacy=get('bb610_market_cart',[]);const migrated=[];legacy.forEach(x=>{const s=defaultSku(x.id);if(s)migrated.push({sku:s.id,qty:x.qty||1})});if(migrated.length)set(LS.cart,migrated)}
  function init(){migrateLegacyCart();renderCategoryNav();updateBadges();updateCompareBar();document.querySelectorAll('[data-search-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();searchSubmit(f)});document.querySelectorAll('[data-mobile-filter]').forEach(b=>b.onclick=()=>document.querySelector('.filters')?.classList.toggle('open'))}
  return {LS,money,get,set,products,byId,sku,defaultSku,commerceItem,pushEvent,trackList,trackSelect,unitPrice,addCart,toggleFav,toggleCompare,updateBadges,toast,productUrl,card,cardV2,bindCards,updateCompareBar,init};
})(); document.addEventListener('DOMContentLoaded',BB610.init);
