document.addEventListener('DOMContentLoaded',async()=>{await BB610_DATA_SOURCE.refresh();
  const root=document.getElementById('cart-root');
  function rows(){return BB610.get(BB610.LS.cart,[]).map(x=>({row:x,sku:BB610.sku(x.sku)})).filter(x=>x.sku).map(x=>({...x,p:BB610.byId(x.sku.product_id)}))}
  function render(){
    const cart=rows();
    if(!cart.length){root.innerHTML='<div class="empty">Кошик порожній. <a class="link" href="catalog.html">Перейти до каталогу</a></div>';BB610.updateBadges();return}
    const allPriced=cart.every(x=>x.sku.price!=null);const total=cart.reduce((s,x)=>s+(x.sku.price==null?0:Number(x.sku.price)*x.row.qty),0);
    BB610.pushEvent('view_cart',{ecommerce:{currency:'UAH',value:allPriced?total:undefined,items:cart.map(x=>BB610.commerceItem(x.sku,x.row.qty))}});
    root.innerHTML=`<div class="cart-layout"><div class="cart-items">${cart.map(x=>`<div class="cart-item compact-cart-item"><a class="cart-thumb" href="${BB610.productUrl(x.p)}"><img src="${x.p.image}" alt="${x.p.name}"></a><div class="cart-product-info"><div class="product-brand">${x.p.brand}</div><a class="cart-product-name" href="${BB610.productUrl(x.p)}">${x.p.name}</a><div class="cart-variant">${x.sku.variant}</div><div class="stock">${x.sku.stock_label}</div></div><div class="cart-qty" aria-label="Кількість"><button class="qty-btn" data-minus="${x.sku.id}" aria-label="Зменшити">−</button><span>${x.row.qty}</span><button class="qty-btn" data-plus="${x.sku.id}" aria-label="Збільшити">+</button></div><div class="cart-side"><b>${x.sku.price==null?'Ціна уточнюється':BB610.money(x.sku.price*x.row.qty)}</b><small>${x.sku.price==null?'':BB610.money(x.sku.price)+' / '+x.sku.variant}</small><button class="cart-remove" data-remove="${x.sku.id}">Видалити</button></div></div>`).join('')}</div><aside class="summary-card"><div class="eyebrow">ПІДСУМОК</div><div class="summary-row"><span>Товари</span><b>${allPriced?BB610.money(total):'Ціна уточнюється'}</b></div><div class="summary-row"><span>Доставка</span><span>уточнюється</span></div><hr style="border:0;border-top:1px solid #30383e"><div class="summary-row" style="font-size:20px"><b>Разом</b><b>${allPriced?BB610.money(total):'Уточнюється'}</b></div><a class="btn" id="checkout-link" style="display:block;text-align:center;margin-top:16px" href="checkout.html">ОФОРМИТИ</a></aside></div>`;
    root.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>chg(b.dataset.plus,1));root.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>chg(b.dataset.minus,-1));root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const target=cart.find(x=>x.sku.id===b.dataset.remove);if(target)BB610.pushEvent('remove_from_cart',{ecommerce:{currency:target.sku.currency||'UAH',value:target.sku.price==null?undefined:Number(target.sku.price)*target.row.qty,items:[BB610.commerceItem(target.sku,target.row.qty)]}});BB610.set(BB610.LS.cart,BB610.get(BB610.LS.cart,[]).filter(x=>x.sku!==b.dataset.remove));render()});BB610.updateBadges();
  }
  function chg(id,d){let c=BB610.get(BB610.LS.cart,[]),x=c.find(x=>x.sku===id);if(x)x.qty=Math.max(1,x.qty+d);BB610.set(BB610.LS.cart,c);render()}
  render();
});
