document.addEventListener('DOMContentLoaded',async()=>{await BB610_DATA_SOURCE.refresh();
 const grid=document.getElementById('catalog-grid'),count=document.getElementById('result-count'),empty=document.getElementById('catalog-empty');const params=new URLSearchParams(location.search);
 const q=document.getElementById('f-q'),culture=document.getElementById('f-culture'),brand=document.getElementById('f-brand'),npk=document.getElementById('f-npk'),active=document.getElementById('f-active'),dnipro=document.getElementById('f-dnipro'),sort=document.getElementById('sort');
 const catGroup=document.querySelector('input[name=cat]')?.closest('.filter-group');if(catGroup){catGroup.innerHTML='<b>Категорія</b><label><input type="radio" name="cat" value="" checked> Усі</label>'+BB610_DATA_SOURCE.categories().filter(c=>c.enabled).sort((a,b)=>a.order-b.order).map(c=>`<label><input type="radio" name="cat" value="${c.id}"> ${c.short_name||c.name}</label>`).join('')}
 brand.innerHTML='<option value="">Усі</option>'+BB610_DATA_SOURCE.catalog().brands.filter(b=>b.enabled).map(b=>`<option>${b.name}</option>`).join('');
 q.value=params.get('q')||'';culture.value=params.get('culture')||'';const cat=window.BB610_CATEGORY_ID||params.get('category')||'';document.querySelector(`input[name=cat][value="${cat}"]`)?.click();
 function render(){let all=[...BB610.products()];const catv=document.querySelector('input[name=cat]:checked').value;const qq=q.value.toLowerCase().trim();if(qq)all=all.filter(x=>{const skus=BB610_DATA_SOURCE.skusForProduct(x.id).map(s=>s.id+' '+s.sku+' '+s.variant);return [x.name,x.brand,x.manufacturer,x.categoryLabel,x.category,...skus,...x.cultures,...x.purposes].join(' ').toLowerCase().includes(qq)});if(catv)all=all.filter(x=>x.category===catv);if(culture.value)all=all.filter(x=>x.cultures.includes(culture.value));if(brand.value)all=all.filter(x=>x.brand===brand.value);if(npk.value)all=all.filter(x=>(x.npk||'').toLowerCase().includes(npk.value.toLowerCase()));if(active.value)all=all.filter(x=>(x.activeIngredient||'').toLowerCase().includes(active.value.toLowerCase()));if(dnipro.checked)all=all.filter(x=>x.stockStatus==='dnipro');if(sort.value==='price-asc')all.sort((a,b)=>(a.price==null?Infinity:a.price)-(b.price==null?Infinity:b.price));if(sort.value==='price-desc')all.sort((a,b)=>(b.price==null?-Infinity:b.price)-(a.price==null?-Infinity:a.price));if(sort.value==='name')all.sort((a,b)=>a.name.localeCompare(b.name,'uk'));count.textContent=`${all.length} товарів`;grid.innerHTML=all.map(BB610.cardV2).join('');empty.style.display=all.length?'none':'block';BB610.bindCards(grid);BB610.trackList(all,'catalog','Каталог')}
 [q,culture,brand,npk,active,dnipro,sort,...document.querySelectorAll('input[name=cat]')].forEach(el=>el.addEventListener(el.tagName==='INPUT'&&el.type==='text'?'input':'change',render));document.getElementById('reset-filters').onclick=()=>{q.value='';culture.value='';brand.value='';npk.value='';active.value='';dnipro.checked=false;document.querySelector('input[name=cat][value=""]').checked=true;sort.value='default';history.replaceState(null,'','catalog.html');render()};render();
});
