document.addEventListener('DOMContentLoaded',()=>{
 const root=document.getElementById('checkout-app');if(!root)return;
 const cart=BB610.get(BB610.LS.cart,[]).map(row=>({row,sku:BB610.sku(row.sku)})).filter(x=>x.sku).map(x=>({...x,p:BB610.byId(x.sku.product_id)}));
 const orderable=x=>x.sku.commercial_status==='active'&&x.sku.offer_status==='active'&&x.sku.price!=null&&x.sku.availability!=='unknown'&&x.sku.availability!=='out_of_stock';
 const allOrderable=cart.length>0&&cart.every(orderable),total=cart.reduce((s,x)=>s+(x.sku.price==null?0:Number(x.sku.price)*x.row.qty),0),configured=BB610OrderClient.configured();
 root.innerHTML=`<div class="checkout-layout"><form id="checkout-form" class="checkout-form" novalidate>
 <div class="info-card checkout-card"><div class="eyebrow">КОНТАКТНІ ДАНІ</div><h2>Оформлення без реєстрації</h2><div class="field-grid"><label><span>Ім’я *</span><input name="name" autocomplete="name" required></label><label><span>Телефон *</span><input name="phone" inputmode="tel" autocomplete="tel" placeholder="+380..." required></label></div><label><span>Email</span><input name="email" type="email" autocomplete="email"></label></div>
 <div class="info-card checkout-card delivery-card"><div class="eyebrow">ДОСТАВКА</div><h2>Спосіб отримання</h2><label><span>Служба / спосіб *</span><select name="provider" id="delivery-provider" required><option value="nova_poshta">Нова пошта</option><option value="pickup_dnipro">Самовивіз у Дніпрі</option><option value="delivery_dnipro">Доставка по Дніпру</option><option value="ukrposhta">Укрпошта</option></select></label><div id="delivery-fields"></div><div id="delivery-api-note" class="delivery-api-note"></div></div>
 <div class="info-card checkout-card payment-card"><div class="eyebrow">ОПЛАТА</div><h2>Спосіб оплати</h2><div id="payment-methods"></div><div id="payment-note" class="delivery-api-note"></div></div>
 <div class="info-card checkout-card"><label><span>Коментар</span><textarea name="comment" rows="2"></textarea></label></div>
 <div class="info-card checkout-card checkout-consent"><label class="consent-row"><input type="checkbox" name="terms_accept" required><span>Підтверджую ознайомлення з <a href="terms.html" target="_blank">умовами продажу</a>, <a href="delivery.html" target="_blank">доставкою</a>, <a href="returns.html" target="_blank">поверненням</a> та <a href="privacy.html" target="_blank">політикою конфіденційності</a>.</span></label></div>
 <div class="checkout-system-note ${configured&&allOrderable?'ready':'blocked'}"><b>${configured&&allOrderable?'Замовлення готове до відправки.':'Оформлення тимчасово недоступне.'}</b><span>${configured&&allOrderable?'Backend повторно перевірить SKU, ціну, наявність і дані доставки.':'Перевірте підключення backend та комерційні дані SKU.'}</span></div>
 <button id="submit-order" class="btn checkout-submit" type="submit" disabled>ПІДТВЕРДИТИ ЗАМОВЛЕННЯ</button><div id="checkout-error" class="checkout-error" hidden></div></form>
 <aside class="summary-card checkout-summary"><div class="eyebrow">ВАШЕ ЗАМОВЛЕННЯ</div>${cart.length?cart.map(x=>`<div class="checkout-line"><div><b>${x.p.name}</b><span>${x.sku.variant} · SKU ${x.sku.id}</span></div><span>${x.row.qty} × ${BB610.money(x.sku.price)}</span></div>`).join(''):'<div class="empty">Кошик порожній.</div>'}<div class="summary-row"><b>Товари</b><b>${BB610.money(total)}</b></div><div class="summary-row delivery-summary"><span>Доставка</span><span>За тарифами перевізника</span></div></aside></div>`;
 const form=document.getElementById('checkout-form'),provider=document.getElementById('delivery-provider'),fields=document.getElementById('delivery-fields'),apiNote=document.getElementById('delivery-api-note'),paymentBox=document.getElementById('payment-methods'),paymentNote=document.getElementById('payment-note'),btn=document.getElementById('submit-order'),err=document.getElementById('checkout-error');
 let capabilities={},paymentCapabilities=[],selectedCity=null,selectedBranch=null,cityTimer=null,branchTimer=null;
 const note=t=>apiNote.textContent=t||'';
 function paymentReady(){return !!form.elements.payment_method?.value}
 function deliveryReady(){if(provider.value!=='nova_poshta')return true;return !!(form.elements.city_ref?.value&&form.elements.branch_ref?.value)}
 function updateSubmit(){btn.disabled=!(configured&&allOrderable&&paymentReady()&&deliveryReady())}
 function renderPayments(){const p=provider.value;paymentBox.innerHTML=(paymentCapabilities||[]).map(m=>{let label=m.label,small='';if(m.id==='cod'&&p==='nova_poshta'){label='Післяплата Nova Poshta / NovaPay';small=m.enabled?'Оплата товару при отриманні. Комісія — за тарифами NovaPay/перевізника.':'Післяплата ще не активована на backend.'}else if(m.id==='online_card'){small=m.enabled?'Після створення замовлення відкриється захищена платіжна сторінка.':'Онлайн-оплата буде підключена на Stage 14.'}else small=m.enabled?'Оплата при отриманні згідно з умовами доставки.':'Спосіб оплати недоступний.';return `<label class="payment-option ${m.enabled?'':'is-disabled'}"><input type="radio" name="payment_method" value="${m.id}" ${m.enabled?'required':'disabled'}><span><b>${label}</b><small>${small}</small></span></label>`}).join('');const first=paymentBox.querySelector('input:not(:disabled)');if(first)first.checked=true;paymentNote.textContent=first?'Спосіб оплати буде перевірено backend під час створення замовлення.':'Немає активного способу оплати.';paymentBox.querySelectorAll('input').forEach(x=>x.onchange=updateSubmit);updateSubmit()}
 async function loadPayment(){try{const r=await BB610OrderClient.paymentMethods();paymentCapabilities=r.methods||[];renderPayments()}catch{paymentNote.textContent='Не вдалося отримати способи оплати.'}}
 async function loadCapabilities(){try{const r=await BB610DeliveryClient.providers();(r.providers||[]).forEach(x=>capabilities[x.provider]=x)}catch{}renderDelivery()}
 function renderDelivery(){selectedCity=null;selectedBranch=null;const p=provider.value,cap=capabilities[p];
   if(p==='pickup_dnipro'){fields.innerHTML='<div class="delivery-static"><b>Дніпро</b><span>Деталі самовивозу підтвердить менеджер.</span></div>';note('');renderPayments();updateSubmit();return}
   if(p==='delivery_dnipro'){fields.innerHTML='<label><span>Адреса доставки *</span><input name="address_line" required></label>';note('');renderPayments();updateSubmit();return}
   if(p!=='nova_poshta'){fields.innerHTML='<label><span>Населений пункт *</span><input name="city" required></label><label><span>Відділення *</span><input name="branch" required></label>';note('Довідник цього перевізника поки не підключений.');renderPayments();updateSubmit();return}
   fields.innerHTML=`<label><span>Тип отримання *</span><select name="service" id="np-service"><option value="branch">Відділення</option><option value="locker">Поштомат</option></select></label>
   <label><span>Місто *</span><input id="delivery-city" name="city" autocomplete="off" placeholder="Наприклад: Дніпро" required><div class="delivery-suggest" id="city-suggest"></div></label><input type="hidden" name="city_ref">
   <label><span id="np-point-label">Відділення *</span><input id="delivery-branch-search" autocomplete="off" placeholder="Пошук за номером або адресою" disabled><select id="delivery-branch-select" name="branch" required disabled><option value="">Спочатку виберіть місто</option></select></label><input type="hidden" name="branch_ref">
   <div class="delivery-choice-state" id="delivery-choice-state">Місто та точка отримання ще не вибрані.</div>`;
   note(cap?.live_lookup?'Довідник Nova Poshta підключений. Виберіть місто, потім відділення або поштомат зі списку.':'API Nova Poshta недоступний.');
   bindNovaPoshta();renderPayments();updateSubmit();
 }
 function bindNovaPoshta(){const city=document.getElementById('delivery-city'),cs=document.getElementById('city-suggest'),service=document.getElementById('np-service'),search=document.getElementById('delivery-branch-search'),select=document.getElementById('delivery-branch-select'),state=document.getElementById('delivery-choice-state'),label=document.getElementById('np-point-label');
   async function loadPoints(q=''){if(!selectedCity?.ref)return;select.disabled=true;select.innerHTML='<option value="">Завантаження…</option>';try{const r=await BB610DeliveryClient.branches('nova_poshta',selectedCity.ref,q,100);const rows=(r.items||[]).filter(x=>!x.service||x.service===service.value);select.innerHTML='<option value="">Оберіть '+(service.value==='locker'?'поштомат':'відділення')+'</option>'+rows.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');select._rows=rows;select.disabled=false;search.disabled=false;state.textContent=`Знайдено ${rows.length} ${service.value==='locker'?'поштоматів':'відділень'}.`;selectedBranch=null;form.elements.branch_ref.value='';updateSubmit()}catch(e){select.innerHTML='<option value="">Не вдалося завантажити список</option>';state.textContent='Помилка Nova Poshta: '+e.message}}
   city.addEventListener('input',()=>{selectedCity=null;selectedBranch=null;form.elements.city_ref.value='';form.elements.branch_ref.value='';select.disabled=true;search.disabled=true;clearTimeout(cityTimer);const q=city.value.trim();if(q.length<2){cs.innerHTML='';updateSubmit();return}cityTimer=setTimeout(async()=>{try{const r=await BB610DeliveryClient.cities('nova_poshta',q,20);const rows=r.items||[];cs.innerHTML=rows.map((x,i)=>`<button type="button" data-i="${i}"><b>${x.name}</b>${x.region?`<small>${x.region}</small>`:''}</button>`).join('');[...cs.children].forEach((b,i)=>b.onclick=()=>{selectedCity=rows[i];city.value=rows[i].name;form.elements.city_ref.value=rows[i].ref||'';cs.innerHTML='';loadPoints('')})}catch(e){cs.innerHTML='';state.textContent='Помилка пошуку міста: '+e.message}},250)});
   service.onchange=()=>{label.textContent=(service.value==='locker'?'Поштомат':'Відділення')+' *';search.placeholder=service.value==='locker'?'Пошук поштомата':'Пошук за номером або адресою';if(selectedCity)loadPoints(search.value.trim())};
   search.oninput=()=>{clearTimeout(branchTimer);branchTimer=setTimeout(()=>loadPoints(search.value.trim()),250)};
   select.onchange=()=>{const rows=select._rows||[],x=rows[Number(select.value)];selectedBranch=x||null;form.elements.branch_ref.value=x?.ref||'';state.textContent=x?`Обрано: ${x.name}`:'Точка отримання не вибрана.';updateSubmit()};
 }
 provider.onchange=renderDelivery;
 form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity()||!configured||!allOrderable||!paymentReady()||!deliveryReady())return;err.hidden=true;btn.disabled=true;btn.textContent='СТВОРЕННЯ ЗАМОВЛЕННЯ…';const fd=new FormData(form),p=String(fd.get('provider')||'');const fulfillment={method:p,provider:p,service:String(fd.get('service')||({pickup_dnipro:'pickup',delivery_dnipro:'courier',nova_poshta:'branch',ukrposhta:'branch'}[p]||'')),city:String(fd.get('city')||'').trim()||null,city_ref:String(fd.get('city_ref')||'').trim()||null,branch:selectedBranch?.name||String(fd.get('branch')||'').trim()||null,branch_ref:String(fd.get('branch_ref')||'').trim()||null,address_line:String(fd.get('address_line')||'').trim()||null};const payload={payment:{method:String(fd.get('payment_method')||'')},customer:{name:String(fd.get('name')||'').trim(),phone:String(fd.get('phone')||'').trim(),email:String(fd.get('email')||'').trim()||null},fulfillment,comment:String(fd.get('comment')||'').trim()||null,currency:'UAH',items:cart.map(x=>({sku:x.sku.id,quantity:x.row.qty})),source:{channel:'web',site:'market.bb610.com.ua'}};try{const result=await BB610OrderClient.createOrder(payload);sessionStorage.setItem('bb610_pending_order',JSON.stringify({order_id:result.order_id,public_token:result.public_token||null}));location.href=result.payment?.redirect_url||result.confirmation_url||`order/success/?order=${encodeURIComponent(result.order_id)}&token=${encodeURIComponent(result.public_token||'')}`}catch(ex){err.hidden=false;err.textContent=ex.data?.detail||ex.message||'Не вдалося створити замовлення.';btn.disabled=false;btn.textContent='ПІДТВЕРДИТИ ЗАМОВЛЕННЯ'}});
 if(configured){loadPayment();loadCapabilities()}else{renderDelivery();renderPayments()}
});
