document.addEventListener('DOMContentLoaded',async()=>{
  await BB610_DATA_SOURCE.refresh();
  const root=document.getElementById('compare-root');
  const ids=BB610.get(BB610.LS.compare,[]),ps=ids.map(BB610.byId).filter(Boolean);
  if(!ps.length){root.innerHTML='<div class="empty">Додайте 2–4 товари через кнопку ⇄ у каталозі.</div>';return}
  const head=p=>{const s=BB610.defaultSku(p.id);const title=BB610.skuName?.(p,s)||p.name;const potVariant=p.category==='containers'?`<span>${s?.variant||p.pack||'Фасовка уточнюється'}</span>`:'';return `<div class="compare-product-header"><a class="compare-product-image" href="${BB610.productUrl(p,s)}"><img src="${p.image}" alt="${title}"></a><div class="compare-product-meta"><a class="compare-product-name" href="${BB610.productUrl(p,s)}">${title}</a><span>${p.manufacturer||p.brand}</span>${potVariant}<b>${BB610.isPriceRequestSku?.(s)?'Ціна за запитом':BB610.money(s?.price??p.price)}</b><small>${BB610.isPriceRequestSku?.(s)?'Під замовлення':(s?.stock_label||p.stockLabel||'Наявність уточнюється')}</small></div><button class="compare-remove" data-remove="${p.id}" aria-label="Прибрати ${title}">×</button></div>`};
  const rows=[['Виробник',p=>p.brand],['Категорія',p=>p.categoryLabel],['Склад / NPK',p=>p.npk||'—'],['Призначення виробника',p=>p.manufacturerUse],['Культури',p=>p.cultures.join(', ')],['Норма застосування',p=>p.rate],['Фасовка',p=>p.pack],['Ціна',p=>{const s=BB610.defaultSku(p.id);return BB610.isPriceRequestSku?.(s)?'Ціна за запитом':BB610.money(p.price)}],['Ціна за одиницю',p=>{const s=BB610.defaultSku(p.id);return BB610.isPriceRequestSku?.(s)?'—':(BB610.unitPrice(p)||'Уточнюється')}],['Наявність',p=>{const s=BB610.defaultSku(p.id);return BB610.isPriceRequestSku?.(s)?'Під замовлення':p.stockLabel}],['Походження',p=>`${p.manufacturer}; ${p.country}; постачальник: ${p.supplier}`]];
  root.innerHTML=`<div class="compare-hint">На смартфоні таблицю можна гортати горизонтально.</div><div class="compare-table-wrap" tabindex="0"><table class="compare-table"><thead><tr><th>Товар</th>${ps.map(p=>`<th>${head(p)}</th>`).join('')}</tr></thead><tbody>${rows.map(([n,f])=>`<tr><td>${n}</td>${ps.map(p=>`<td>${f(p)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{BB610.toggleCompare(b.dataset.remove);location.reload()});
});