(()=>{
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], cfg=window.BB610_ADMIN_CONFIG||{};
 const api=$('#api'),token=$('#token'),login=$('#login'),app=$('#app'),orders=$('#orders'),status=$('#status'),summary=$('#summary'),dlg=$('#detail'),detail=$('#detail-body');
 api.value=sessionStorage.getItem('bb610_admin_api')||cfg.apiBaseUrl||'';token.value=sessionStorage.getItem('bb610_admin_token')||'';
 const money=n=>new Intl.NumberFormat('uk-UA',{style:'currency',currency:'UAH'}).format(Number(n||0));
 async function req(path,opt={}){const base=(api.value||'').replace(/\/$/,'');if(!/^https?:\/\//.test(base))throw new Error('Вкажіть URL Commerce API');const c=new AbortController(),t=setTimeout(()=>c.abort(),cfg.requestTimeoutMs||12000);try{const r=await fetch(base+path,{...opt,signal:c.signal,headers:{Accept:'application/json',Authorization:'Bearer '+token.value,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
 function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function showTab(name){$$('.admin-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.hidden=p.id!==`tab-${name}`);if(name==='orders')loadOrders();if(name==='approvals')loadApprovals();if(name==='jobs')loadJobs();if(name==='rules')loadRules();if(name==='audit')loadAudit()}
 $$('.admin-tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
 async function refreshAutomationSummary(){try{const s=await req('/api/v1/admin/automation/summary');$('#approval-count').textContent=s.approvals_pending?`(${s.approvals_pending})`:'';$('#ai-summary').textContent=`queued ${s.ai_jobs_queued} · blocked ${s.ai_jobs_blocked} · provider ${s.ai_provider_configured?'ON':'OFF'}`}catch{}}
 let orderData=[];
 const statusName=v=>({new:'Новий',confirmed:'Підтверджено',preparing:'Комплектується',shipped:'Відправлено',completed:'Виконано',cancelled:'Скасовано'}[v]||v);
 function renderOrders(){const q=($('#order-search')?.value||'').toLowerCase().trim();const list=orderData.filter(o=>!q||[o.order_number,o.customer_name,o.customer_phone,o.customer_email,o.fulfillment_destination].join(' ').toLowerCase().includes(q));summary.textContent=`${list.length} із ${orderData.length} замовлень`;orders.innerHTML=list.length?list.map(o=>`<article class="order-row" data-id="${esc(o.id)}"><div><div class="order-num">${esc(o.order_number)}</div><div class="muted">${new Date(o.created_at).toLocaleString('uk-UA')}</div></div><div><b>${esc(o.customer_name)}</b><div class="muted">${esc(o.customer_phone)}</div></div><div>${o.items.length} поз.</div><div class="status status-label">${esc(statusName(o.status))}</div><div class="money">${money(o.total)}</div><div class="muted">${esc(o.delivery?.provider||o.fulfillment_method||'—')}</div></article>`).join(''):'<div class="detail-card">Нічого не знайдено.</div>';$$('.order-row').forEach(x=>x.onclick=()=>openOrder(x.dataset.id))}
 async function loadOrders(){orders.innerHTML='<div class="detail-card">Завантаження…</div>';let q=status.value?'?status='+encodeURIComponent(status.value):'';try{const d=await req('/api/v1/admin/orders'+q);orderData=d.orders||[];renderOrders()}catch(e){orders.innerHTML=`<div class="detail-card">${esc(e.message)}</div>`}}
 async function openOrder(id){try{const o=await req('/api/v1/admin/orders/'+encodeURIComponent(id));const transitions={new:['confirmed'],confirmed:['preparing'],preparing:['shipped'],shipped:['completed'],completed:[],cancelled:[]};const tel=(o.customer_phone||'').replace(/[^+\d]/g,'');detail.innerHTML=`<div class="detail-card"><h2>${esc(o.order_number)}</h2><div class="detail-grid"><div><span class="muted">Статус</span><br><b>${esc(statusName(o.status))}</b></div><div><span class="muted">Створено</span><br>${new Date(o.created_at).toLocaleString('uk-UA')}</div><div><span class="muted">Сума</span><br><b>${money(o.total)}</b></div></div></div>
<div class="detail-card"><h3>Покупець</h3><div><b>${esc(o.customer_name)}</b></div><div>${esc(o.customer_phone)}</div><div>${esc(o.customer_email||'—')}</div><div class="contact-links">${tel?`<a href="tel:${esc(tel)}">Подзвонити</a>`:''}${o.customer_email?`<a href="mailto:${esc(o.customer_email)}">Написати e-mail</a>`:''}</div>${o.comment?`<div style="margin-top:12px"><span class="muted">Коментар покупця</span><br>${esc(o.comment)}</div>`:''}</div>
<div class="detail-card"><h3>Товари</h3>${o.items.map(i=>`<div class="detail-line"><div><b>${esc(i.name)}</b><div class="muted">${esc(i.variant||'—')} · ${esc(i.sku)}</div></div><div>${i.quantity} × ${money(i.unit_price)}<br><b>${money(i.line_total)}</b></div></div>`).join('')}</div>
<div class="detail-card"><h3>Доставка</h3>${o.delivery?`<div><b>${esc(o.delivery.provider||'—')} · ${esc(o.delivery.service||'—')}</b></div><div>${esc([o.delivery.city,o.delivery.branch,o.delivery.address_line].filter(Boolean).join(' · ')||'—')}</div><div class="muted" style="margin-top:6px">Отримувач: ${esc(o.delivery.recipient_name||o.customer_name||'—')} · ${esc(o.delivery.recipient_phone||o.customer_phone||'—')}</div><div style="margin-top:8px">ТТН: <b>${esc(o.delivery.tracking_number||'не створена')}</b></div>${o.delivery.provider==='nova_poshta'&&!o.delivery.tracking_number?`<div class="tracking-box"><button id="create-np-ttn">СТВОРИТИ ТТН NOVA POSHTA</button></div>`:`<div class="tracking-box"><input id="tracking-number" value="${esc(o.delivery.tracking_number||'')}" placeholder="Номер ТТН"><button id="save-tracking">ЗБЕРЕГТИ ТТН</button>${o.delivery.tracking_number?'<button id="refresh-tracking">ОНОВИТИ СТАТУС</button>':''}</div>`}${o.delivery.carrier_status_text?`<div class="muted" style="margin-top:8px">${esc(o.delivery.carrier_status_text)}</div>`:''}`:'<div class="muted">Дані доставки відсутні.</div>'}</div>
<div class="detail-card"><h3>Оплата</h3><div><b>${esc(o.payment?.method||o.payment_method||'—')}</b> · <span class="status">${esc(o.payment?.status||o.payment_status||'—')}</span></div></div>
<div class="detail-card"><h3>Статус замовлення</h3>${(transitions[o.status]||[]).length?`<div class="status-controls"><select id="new-status">${transitions[o.status].map(s=>`<option value="${s}">${statusName(s)}</option>`).join('')}</select><input id="status-note" placeholder="Коментар до зміни статусу"><button id="save-status">ЗБЕРЕГТИ</button></div>`:'<div class="muted">Фінальний статус.</div>'}${!['completed','cancelled'].includes(o.status)?`<div style="margin-top:10px"><button id="request-cancel" class="dialog-close">ЗАПРОСИТИ СКАСУВАННЯ</button></div>`:''}</div>
<div class="detail-card"><h3>Внутрішні нотатки</h3>${(o.admin_notes||[]).map(n=>`<div class="note-row">${esc(n.note)}<div class="muted">${new Date(n.created_at).toLocaleString('uk-UA')}</div></div>`).join('')||'<div class="muted">Нотаток немає.</div>'}<div class="note-box"><textarea id="admin-note" placeholder="Нотатка менеджера — покупець її не бачить"></textarea><button id="save-note">ДОДАТИ</button></div></div>
<div class="detail-card"><h3>Історія</h3>${o.history.map(h=>`<div class="detail-line"><div>${esc(h.from_status?statusName(h.from_status):'—')} → <b>${esc(statusName(h.to_status))}</b><div class="muted">${esc(h.note||'')}</div></div><div class="muted">${new Date(h.created_at).toLocaleString('uk-UA')}</div></div>`).join('')}</div>`;dlg.showModal();
const save=$('#save-status');if(save)save.onclick=async()=>{await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:$('#new-status').value,note:$('#status-note').value||null})});await openOrder(id);loadOrders();refreshAutomationSummary()};
const createTtn=$('#create-np-ttn');if(createTtn)createTtn.onclick=async()=>{if(!confirm('Створити реальну ТТН Nova Poshta для цього замовлення?'))return;createTtn.disabled=true;createTtn.textContent='СТВОРЕННЯ…';try{const r=await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/delivery/create-shipment',{method:'POST'});alert('ТТН створено: '+(r.tracking_number||''));await openOrder(id);loadOrders()}catch(e){alert(e.message);createTtn.disabled=false;createTtn.textContent='СТВОРИТИ ТТН NOVA POSHTA'}};
const tr=$('#save-tracking');if(tr)tr.onclick=async()=>{const v=$('#tracking-number').value.trim();if(!v)return alert('Вкажіть номер ТТН');await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/delivery/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tracking_number:v,note:'Вказано менеджером'})});await openOrder(id)};
const rt=$('#refresh-tracking');if(rt)rt.onclick=async()=>{rt.disabled=true;try{await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/delivery/refresh',{method:'POST'});await openOrder(id)}catch(e){alert(e.message);rt.disabled=false}};
const note=$('#save-note');if(note)note.onclick=async()=>{const v=$('#admin-note').value.trim();if(!v)return;await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:v})});await openOrder(id)};
const cancel=$('#request-cancel');if(cancel)cancel.onclick=async()=>{await req('/api/v1/admin/orders/'+encodeURIComponent(id)+'/cancel-request',{method:'POST'});dlg.close();refreshAutomationSummary();showTab('approvals')}}catch(e){alert(e.message)}}
 async function loadApprovals(){const el=$('#approvals');el.innerHTML='<div class="detail-card">Завантаження…</div>';try{const d=await req('/api/v1/admin/automation/approvals?status=pending');el.innerHTML=d.approvals.length?d.approvals.map(a=>`<article class="automation-row"><div><b>${esc(a.title)}</b><div class="muted">${esc(a.action_type)} · risk ${esc(a.risk_level)}</div></div><div><code>${esc(a.source_id||'')}</code></div><div class="status">${esc(a.status)}</div><div class="approval-actions"><button class="approve" data-id="${esc(a.id)}" data-decision="approved">OK</button><button class="reject" data-id="${esc(a.id)}" data-decision="rejected">НІ</button></div></article>`).join(''):'<div class="detail-card">Немає рішень, що очікують.</div>';$$('[data-decision]').forEach(b=>b.onclick=async()=>{const note=prompt('Коментар до рішення (необов’язково)')||null;await req('/api/v1/admin/automation/approvals/'+encodeURIComponent(b.dataset.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:b.dataset.decision,note})});loadApprovals();refreshAutomationSummary()})}catch(e){el.innerHTML=`<div class="detail-card">${esc(e.message)}</div>`}}
 async function loadJobs(){const el=$('#jobs');try{const d=await req('/api/v1/admin/automation/jobs');el.innerHTML=d.jobs.length?d.jobs.map(j=>`<article class="automation-row"><div><b>${esc(j.job_type)}</b><div class="muted">${esc(j.context_scope)}</div></div><div><code>${esc(j.aggregate_type)}:${esc(j.aggregate_id)}</code></div><div class="status">${esc(j.status)}</div><div class="muted">${new Date(j.created_at).toLocaleString('uk-UA')}</div></article>`).join(''):'<div class="detail-card">AI-задач поки немає.</div>';refreshAutomationSummary()}catch(e){el.innerHTML=`<div class="detail-card">${esc(e.message)}</div>`}}
 async function loadRules(){const el=$('#rules');try{const d=await req('/api/v1/admin/automation/rules');el.innerHTML=d.rules.map(r=>`<article class="automation-row"><div><b>${esc(r.name)}</b><div class="muted">${esc(r.event_type)}</div></div><div><span class="mode">${esc(r.mode)}</span><div class="muted">${esc(r.action_type)}</div></div><div><code>${esc(r.id)}</code></div><div><button class="switch-btn ${r.enabled?'on':''}" data-rule="${esc(r.id)}" data-enabled="${r.enabled?1:0}">${r.enabled?'ON':'OFF'}</button></div></article>`).join('');$$('[data-rule]').forEach(b=>b.onclick=async()=>{await req('/api/v1/admin/automation/rules/'+encodeURIComponent(b.dataset.rule),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:b.dataset.enabled!=='1'})});loadRules();refreshAutomationSummary()})}catch(e){el.innerHTML=`<div class="detail-card">${esc(e.message)}</div>`}}
 async function loadAudit(){const el=$('#audit');try{const d=await req('/api/v1/admin/automation/audit?limit=200');el.innerHTML=d.entries.length?d.entries.map(x=>`<article class="audit-row"><div class="muted">${new Date(x.created_at).toLocaleString('uk-UA')}</div><div><b>${esc(x.action)}</b><div class="muted">${esc(x.actor_type)} ${esc(x.actor_id||'')}</div></div><div><code>${esc(x.target_type||'')} ${esc(x.target_id||'')}</code></div></article>`).join(''):'<div class="detail-card">Audit log порожній.</div>'}catch(e){el.innerHTML=`<div class="detail-card">${esc(e.message)}</div>`}}
 $('#connect').onclick=async()=>{sessionStorage.setItem('bb610_admin_api',api.value);sessionStorage.setItem('bb610_admin_token',token.value);try{await req('/api/v1/admin/orders?limit=1');login.hidden=true;app.hidden=false;loadOrders();refreshAutomationSummary()}catch(e){alert(e.message)}};$('#refresh').onclick=loadOrders;status.onchange=loadOrders;const os=$('#order-search');if(os)os.oninput=renderOrders;if(api.value&&token.value){req('/api/v1/admin/orders?limit=1').then(()=>{login.hidden=true;app.hidden=false;loadOrders();refreshAutomationSummary()}).catch(()=>{})}
})();
