(()=>{'use strict';const API='https://api.market.bb610.com.ua';let events=[],active='';const $=s=>document.querySelector(s);const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());load()};$('#refresh').onclick=load;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function dt(ts){return ts?new Date(ts*1000).toLocaleString('uk-UA'):'—'}
function filter(){const q=$('#search').value.trim().toLowerCase(),m=$('#module').value,a=$('#action').value,df=$('#dateFrom').value?new Date($('#dateFrom').value+'T00:00:00').getTime()/1000:0,dtv=$('#dateTo').value?new Date($('#dateTo').value+'T23:59:59').getTime()/1000:Infinity;return events.filter(e=>{const hay=(e.module+' '+e.action+' '+e.object+' '+e.actor+' '+e.commit+' '+e.summary+' '+JSON.stringify(e.raw||{})).toLowerCase();if(q&&!hay.includes(q))return false;if(m&&e.module!==m)return false;if(a&&e.action!==a)return false;if(e.time<df||e.time>dtv)return false;return true})}
function render(){const list=filter();$('#count').textContent=list.length+' подій';$('#rows').innerHTML=list.map(e=>`<tr data-id="${esc(e.id)}" class="${active===e.id?'active':''}"><td>${dt(e.time)}</td><td><span class="badge ${esc(e.module)}">${esc(e.module)}</span></td><td>${esc(e.action)}</td><td>${esc(e.object||'—')}</td><td>${esc(e.actor||'—')}</td><td>${esc(e.commit||'—')}</td></tr>`).join('')||'<tr><td colspan=6>Подій не знайдено.</td></tr>';document.querySelectorAll('tbody tr[data-id]').forEach(r=>r.onclick=()=>{active=r.dataset.id;detail(active);render()})}
function detail(id){const e=events.find(x=>x.id===id);if(!e)return;$('#detail').innerHTML=`<h2>${esc(e.action)}</h2><div class=meta>${dt(e.time)} · ${esc(e.module)} · ${esc(e.actor||'—')}</div><div class=summary>${esc(e.summary||'')}</div><div class=meta>Object: ${esc(e.object||'—')}<br>Commit: ${esc(e.commit||'—')}</div><pre class=raw>${esc(JSON.stringify(e.raw||{},null,2))}</pre>`}
['search','module','action','dateFrom','dateTo'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));
$('#csv').onclick=async()=>{try{const r=await fetch(API+'/api/v1/admin/audit-log.csv',{headers:{Authorization:'Bearer '+token()}});if(!r.ok)throw new Error('CSV export error');const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='bb610-audit-log.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert(e.message)}};
async function load(){try{const x=await api('/api/v1/admin/audit-log',{headers:{Authorization:'Bearer '+token()}});events=x.events||[];$('#total').textContent=x.count||0;$('#modulesCount').textContent=Object.keys(x.modules||{}).length;$('#lastEvent').textContent=events.length?dt(events[0].time):'—';$('#module').innerHTML='<option value="">Усі модулі</option>'+Object.keys(x.modules||{}).sort().map(v=>`<option>${esc(v)}</option>`).join('');$('#action').innerHTML='<option value="">Усі дії</option>'+Object.keys(x.actions||{}).sort().map(v=>`<option>${esc(v)}</option>`).join('');localStorage.setItem('bb610_admin_token',token());render()}catch(e){alert(e.message)}}
if(token())load();})();