(()=>{'use strict';const API='https://api.market.bb610.com.ua';let backups=[],active='';const $=s=>document.querySelector(s);const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());load()};
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function dt(ts){return ts?new Date(ts*1000).toLocaleString('uk-UA'):'—'}
function filtered(){const q=$('#search').value.trim().toLowerCase(),k=$('#kind').value;return backups.filter(b=>{const hay=(b.id+' '+b.label+' '+b.source+' '+b.kind).toLowerCase();if(q&&!hay.includes(q))return false;if(k&&b.kind!==k)return false;return true})}
function render(){const list=filtered();$('#count').textContent=list.length+' backup';$('#rows').innerHTML=list.map(b=>`<tr data-id="${esc(b.id)}" class="${active===b.id?'active':''}"><td>${dt(b.created_at)}</td><td><b>${esc(b.label||b.id)}</b><br><small>${esc(b.id)}</small></td><td>${esc(b.source)}</td><td><span class="badge ${b.kind}">${esc(b.kind)}</span></td><td>${b.file_count}</td><td>${esc(b.size_human)}</td><td>→</td></tr>`).join('')||'<tr><td colspan=7>Backup не знайдено.</td></tr>';document.querySelectorAll('tbody tr[data-id]').forEach(r=>r.onclick=()=>{active=r.dataset.id;detail(active);render()})}
function detail(id){const b=backups.find(x=>x.id===id);if(!b)return;$('#detail').innerHTML=`<h2>${esc(b.label||b.id)}</h2><div class=meta>${dt(b.created_at)} · ${esc(b.source)} · ${esc(b.size_human)}</div><div class=filelist>${(b.files||[]).map(f=>`<div class=file><span>${esc(f.path)}</span><span>${Math.round((f.size||0)/1024)} KB</span></div>`).join('')||'<div class=file>Немає доступних файлів.</div>'}</div><div class=actions><button class=secondary id=download>Завантажити ZIP</button></div><div class=restore-box><label>Для відновлення введіть RESTORE</label><input id=confirmRestore placeholder="RESTORE"><label><input id=publishGit type=checkbox> Git commit + push після restore</label><button class=danger id=restore>Відновити цей backup</button><small>Перед restore буде автоматично створено safety backup поточного стану.</small></div>`;$('#download').onclick=()=>download(id);$('#restore').onclick=()=>restore(id)}
async function download(id){try{const r=await fetch(API+'/api/v1/admin/backups/'+encodeURIComponent(id)+'/download',{headers:{Authorization:'Bearer '+token()}});if(!r.ok)throw new Error('Download failed');const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=id+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert(e.message)}}
async function restore(id){const confirmText=$('#confirmRestore').value.trim();if(confirmText!=='RESTORE'){alert('Введіть RESTORE');return}if(!confirm('Відновити '+id+'? Перед цим буде створено safety backup.'))return;try{const x=await api('/api/v1/admin/backups/restore',{method:'POST',body:JSON.stringify({backup_id:id,confirm_text:confirmText,publish_git:$('#publishGit').checked})});alert(`Restore завершено. Файлів: ${x.restored_files}. Safety backup: ${x.safety_backup_id}${x.commit?' · commit '+x.commit:''}`);load()}catch(e){alert(e.message)}}
$('#create').onclick=async()=>{const label=prompt('Назва backup:','Manual backup');if(label===null)return;try{const x=await api('/api/v1/admin/backups',{method:'POST',body:JSON.stringify({label:label||'Manual backup'})});alert('Backup створено: '+x.backup.id);load()}catch(e){alert(e.message)}};
['search','kind'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));
async function load(){try{const x=await api('/api/v1/admin/backups',{headers:{Authorization:'Bearer '+token()}});backups=x.backups||[];localStorage.setItem('bb610_admin_token',token());render();if(active&&!backups.some(b=>b.id===active))active=''}catch(e){alert(e.message)}}
if(token())load();})();