(()=>{'use strict';const API='https://api.market.bb610.com.ua';let health=null,dups=null;const $=s=>document.querySelector(s);const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());load()};$('#refresh').onclick=load;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function openHref(id){return 'catalog-workbench.html?q='+encodeURIComponent(id)}
function renderIssues(){const q=$('#issueSearch').value.trim().toLowerCase(),sev=$('#severity').value,code=$('#code').value;const list=(health.issues||[]).filter(i=>{const hay=(i.product_id+' '+i.sku_id+' '+i.label+' '+i.detail+' '+i.code).toLowerCase();if(q&&!hay.includes(q))return false;if(sev&&i.severity!==sev)return false;if(code&&i.code!==code)return false;return true});$('#issueCount').textContent=list.length+' проблем';$('#issueRows').innerHTML=list.map(i=>`<tr><td><span class="sev ${i.severity}">${esc(i.severity)}</span></td><td>${esc(i.product_id||'—')}</td><td>${esc(i.sku_id||'—')}</td><td><b>${esc(i.label)}</b><br><small>${esc(i.code)}</small></td><td>${esc(i.detail||'—')}</td><td><a class=open href="${openHref(i.sku_id||i.product_id)}">Відкрити →</a></td></tr>`).join('')||'<tr><td colspan=6>Проблем не знайдено.</td></tr>'}
function renderDups(){const q=$('#dupSearch').value.trim().toLowerCase(),kind=$('#dupKind').value;const list=(dups.groups||[]).filter(g=>{const hay=(g.reason+' '+g.kind+' '+g.items.map(x=>x.product_id+' '+x.title+' '+x.brand).join(' ')).toLowerCase();if(q&&!hay.includes(q))return false;if(kind&&g.kind!==kind)return false;return true});$('#dupCount').textContent=list.length+' груп';$('#duplicateGroups').innerHTML=list.map(g=>`<article class=dup><div class=dup-head><b>${esc(g.reason)}</b><span>${esc(g.kind)}</span><span class=confidence>${Math.round(g.confidence*100)}%</span></div><div class=dup-items>${g.items.map(x=>`<div class=dup-item><b>${esc(x.title)}</b><small>${esc(x.brand||'—')} · ${esc(x.category||'—')}</small><small>${esc(x.product_id)}</small><a class=open href="${openHref(x.product_id)}">Відкрити в каталозі →</a></div>`).join('')}</div><div class=dup-actions><button class="danger-lite" data-ignore="${esc(g.key)}">Не дубль / ігнорувати</button></div></article>`).join('')||'<div class=dup>Ймовірних дублікатів не знайдено.</div>';document.querySelectorAll('[data-ignore]').forEach(b=>b.onclick=()=>ignoreDup(b.dataset.ignore))}
async function ignoreDup(key){if(!confirm('Позначити цю групу як не дубль? Вона більше не буде показуватись у списку.'))return;try{await api('/api/v1/admin/catalog-health/ignore-duplicate',{method:'POST',body:JSON.stringify({key})});load()}catch(e){alert(e.message)}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#issuesTab').hidden=b.dataset.tab!=='issues';$('#duplicatesTab').hidden=b.dataset.tab!=='duplicates'});
['issueSearch','severity','code'].forEach(id=>$('#'+id).addEventListener(id==='issueSearch'?'input':'change',renderIssues));['dupSearch','dupKind'].forEach(id=>$('#'+id).addEventListener(id==='dupSearch'?'input':'change',renderDups));
async function load(){try{const x=await api('/api/v1/admin/catalog-health',{headers:{Authorization:'Bearer '+token()}});health=x.health;dups=x.duplicates;$('#products').textContent=health.products;$('#skus').textContent=health.skus;$('#critical').textContent=health.counts.critical||0;$('#warning').textContent=health.counts.warning||0;$('#info').textContent=health.counts.info||0;$('#dups').textContent=dups.count||0;const codes=[...new Set((health.issues||[]).map(i=>i.code))].sort();$('#code').innerHTML='<option value="">Усі типи</option>'+codes.map(c=>`<option>${esc(c)}</option>`).join('');localStorage.setItem('bb610_admin_token',token());renderIssues();renderDups()}catch(e){alert(e.message)}}
if(token())load();})();