(()=>{const cfg=window.BB610_ADMIN_CONFIG||{},base=(cfg.apiBaseUrl||'').replace(/\/$/,''),ep=cfg.endpoints?.catalogProducts||'/api/v1/admin/catalog/products',mediaEp=cfg.endpoints?.catalogMedia||'/api/v1/admin/catalog/media';const $=id=>document.getElementById(id);let products=[],current=null,isNew=false,gallery=[];const token=$('token');token.value=sessionStorage.getItem('bb610_admin_token')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const H=json=>({'Authorization':'Bearer '+token.value.trim(),...(json?{'Content-Type':'application/json'}:{})});async function req(path,opt={}){const r=await fetch(base+path,{...opt,headers:{...H(opt.body&&!(opt.body instanceof FormData)),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'HTTP '+r.status);return d}
async function load(){sessionStorage.setItem('bb610_admin_token',token.value.trim());$('state').textContent='Завантаження…';const d=await req(ep);products=d.products||[];render();$('state').textContent=products.length+' товарів'}
function render(){const q=$('search').value.toLowerCase(),f=$('filter').value;const list=products.filter(p=>(!q||[p.name,p.brand,p.id].join(' ').toLowerCase().includes(q))&&(!f||(f==='published'?p.published:!p.published)));$('cards').innerHTML=list.map(p=>`<article class="card" data-id="${esc(p.id)}"><img class="thumb" src="${esc(p.image||'../assets/img/product-biostim.svg')}" onerror="this.src='../assets/img/product-biostim.svg'"><div><div class="name">${esc(p.name)}</div><div class="meta">${esc(p.brand||'')} · ${esc(p.id)} · ${p.sku_count} SKU</div><span class="badge ${p.published?'live':'draft'}">${p.published?'Опубліковано':'Чернетка'}</span> <span class="badge">${esc(p.source)}</span></div></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openExisting(c.dataset.id))}
const lines=v=>(v||[]).join('\n');function imageUrl(path){if(!path)return '';if(/^https?:/.test(path))return path;if(path.startsWith('/media/'))return base+path;return '../'+path.replace(/^\//,'')}
function fill(p){current=p;isNew=false;$('f-id').value=p.id||'';$('f-id').disabled=true;$('f-slug').value=p.slug||'';$('f-name').value=p.name||'';$('f-brand').value=p.brand||'';$('f-category').value=p.category_id||'nutrition';$('f-manufacturer').value=p.manufacturer||'';$('f-country').value=p.country||'';$('f-type').value=p.product_type||'';$('f-form').value=p.form||'';$('f-npk').value=p.npk||'';$('f-active').value=p.active_ingredient||'';$('f-short').value=p.short_description||'';$('f-use').value=p.manufacturer_use||'';$('f-application').value=p.application||'';$('f-rate').value=p.rate||'';$('f-restrictions').value=p.restrictions||'';$('f-cultures').value=lines(p.cultures);$('f-purposes').value=lines(p.purposes);$('f-composition').value=lines(p.composition);$('f-packs').value=lines(p.factory_packs);const im=typeof p.image==='string'?p.image:p.image?.local||'';$('f-image').value=im;$('preview').src=imageUrl(im);gallery=[...(p.gallery||[])];renderGallery();$('f-source-title').value=p.source?.title||'';$('f-source-url').value=p.source?.url||'';$('f-verified').checked=!!p.verification?.verified;$('f-published').checked=!!p.published;$('editor-title').textContent=p.name||'Товар';$('editor-sub').textContent=p.cms_source||'';renderSkus(p.skus||[]);$('save-state').textContent='';$('editor').showModal()}
async function openExisting(id){try{fill(await req(ep+'/'+encodeURIComponent(id)))}catch(e){alert(e.message)}}function openNew(){isNew=true;current=null;document.querySelectorAll('#editor input:not([type=checkbox]):not([type=file]),#editor textarea').forEach(x=>x.value='');$('f-id').disabled=false;$('f-category').value='nutrition';$('f-npk').value='—';$('f-active').value='—';$('f-published').checked=false;$('f-verified').checked=false;$('preview').src='';gallery=[];renderGallery();$('editor-title').textContent='Новий товар';$('editor-sub').textContent='';renderSkus([]);$('editor').showModal()}
function renderSkus(skus){$('sku-list').innerHTML=skus.length?skus.map(s=>`<div class="sku-box"><b>${esc(s.variant||'—')}</b><div class="meta">${esc(s.id||s.sku)} · ${s.price==null?'ціна не вказана':s.price+' грн'} · ${esc(s.availability||'unknown')}</div></div>`).join(''):'<div class="muted">SKU ще немає.</div>'}
function body(){const L=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);return {id:$('f-id').value.trim(),slug:$('f-slug').value.trim(),name:$('f-name').value.trim(),brand:$('f-brand').value.trim(),category_id:$('f-category').value,manufacturer:$('f-manufacturer').value.trim(),country:$('f-country').value.trim(),product_type:$('f-type').value.trim(),form:$('f-form').value.trim(),npk:$('f-npk').value.trim(),active_ingredient:$('f-active').value.trim(),short_description:$('f-short').value.trim(),manufacturer_use:$('f-use').value.trim(),application:$('f-application').value.trim(),rate:$('f-rate').value.trim(),restrictions:$('f-restrictions').value.trim(),cultures:L('f-cultures'),purposes:L('f-purposes'),composition:L('f-composition'),factory_packs:L('f-packs'),image:$('f-image').value.trim(),gallery:[...gallery],source_title:$('f-source-title').value.trim(),source_url:$('f-source-url').value.trim(),verified:$('f-verified').checked,published:$('f-published').checked}}
async function save(forceDraft=false){const b=body();if(forceDraft)b.published=false;if(!b.name)return alert('Вкажіть назву');$('save-state').textContent='Збереження…';try{let p;if(isNew){p=await req(ep,{method:'POST',body:JSON.stringify(b)});isNew=false;$('f-id').disabled=true}else p=await req(ep+'/'+encodeURIComponent(current.id),{method:'PATCH',body:JSON.stringify(b)});fill(p);await load();$('save-state').textContent='Збережено'}catch(e){$('save-state').textContent='Помилка: '+e.message}}

function renderGallery(){$('gallery-preview').innerHTML=gallery.map((x,i)=>`<div style="position:relative"><img class="photo-preview" style="width:100px;height:100px" src="${imageUrl(x)}"><button type="button" class="danger" data-gdel="${i}" style="position:absolute;right:4px;top:4px;padding:4px 7px">×</button></div>`).join('');document.querySelectorAll('[data-gdel]').forEach(b=>b.onclick=()=>{gallery.splice(Number(b.dataset.gdel),1);renderGallery()})}
$('gallery-upload').onchange=async()=>{const files=[...$('gallery-upload').files];for(const f of files){const fd=new FormData();fd.append('file',f);$('save-state').textContent='Завантаження фото…';try{const r=await fetch(base+mediaEp,{method:'POST',headers:H(false),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');gallery.push(d.path)}catch(e){$('save-state').textContent=e.message;return}}renderGallery();$('save-state').textContent='Фото завантажено'};
$('upload').onchange=async()=>{const f=$('upload').files[0];if(!f)return;const fd=new FormData();fd.append('file',f);$('save-state').textContent='Завантаження фото…';try{const r=await fetch(base+mediaEp,{method:'POST',headers:H(false),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');$('f-image').value=d.path;$('preview').src=imageUrl(d.path);$('save-state').textContent='Фото завантажено'}catch(e){$('save-state').textContent=e.message}};
$('add-sku').onclick=async()=>{if(isNew)return alert('Спочатку збережіть товар');const sku={sku:$('sku-code').value.trim(),variant:$('sku-variant').value.trim(),price:$('sku-price').value===''?null:Number($('sku-price').value),availability:$('sku-av').value,enabled:$('sku-enabled').checked,image:$('f-image').value.trim()||null};if(!sku.sku||!sku.variant)return alert('Вкажіть SKU і фасування');try{await req(ep+'/'+encodeURIComponent(current.id)+'/skus',{method:'POST',body:JSON.stringify(sku)});fill(await req(ep+'/'+encodeURIComponent(current.id)));await load()}catch(e){alert(e.message)}};
$('connect').onclick=()=>load().catch(e=>$('state').textContent=e.message);$('add').onclick=openNew;$('close').onclick=()=>$('editor').close();$('save').onclick=()=>save(false);$('save-draft').onclick=()=>save(true);$('search').oninput=render;$('filter').onchange=render;$('f-image').oninput=()=>$('preview').src=imageUrl($('f-image').value.trim());if(token.value)load().catch(e=>$('state').textContent=e.message)})();
