(()=>{'use strict';const API='https://api.market.bb610.com.ua';let cats=[],products=[],selected=new Set(),drag=null;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());load()};
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function renderCats(){const parents=['<option value="">—</option>',...cats.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`)].join('');$('#categories').innerHTML=cats.map((c,i)=>`<div class=cat draggable=true data-i="${i}"><span class=drag>⋮⋮</span><input class=order type=number value="${c.order||((i+1)*10)}"><input class=name value="${esc(c.name)}"><select class=parent>${parents}</select><label><input class=enabled type=checkbox ${c.enabled?'checked':''}> ON</label><span class=count>${c.product_count||0} товарів</span><input class=image placeholder="Зображення" value="${esc(c.image||'')}"><input class=seo placeholder="SEO title" value="${esc(c.seo_title||'')}"><button class=delete>×</button><textarea class=desc placeholder="SEO description">${esc(c.seo_description||'')}</textarea></div>`).join('')||'<div class=empty>Категорій немає</div>';document.querySelectorAll('.cat').forEach((el,i)=>{el.querySelector('.parent').value=cats[i].parent_id||'';el.querySelector('.delete').onclick=()=>del(i);el.addEventListener('dragstart',()=>{syncCats();drag=el;el.style.opacity=.4});el.addEventListener('dragend',()=>{el.style.opacity='';drag=null});el.addEventListener('dragover',e=>{if(drag&&drag!==el)e.preventDefault()});el.addEventListener('drop',e=>{if(!drag||drag===el)return;e.preventDefault();const f=+drag.dataset.i,t=+el.dataset.i,x=cats.splice(f,1)[0];cats.splice(t,0,x);cats.forEach((c,j)=>c.order=(j+1)*10);renderCats()})});renderMoveCats()}
function syncCats(){document.querySelectorAll('.cat').forEach((el,i)=>{const c=cats[i];c.order=+el.querySelector('.order').value||((i+1)*10);c.name=el.querySelector('.name').value.trim();c.parent_id=el.querySelector('.parent').value;c.enabled=el.querySelector('.enabled').checked;c.image=el.querySelector('.image').value.trim();c.seo_title=el.querySelector('.seo').value.trim();c.seo_description=el.querySelector('.desc').value.trim()})}
function renderMoveCats(){$('#moveCategory').innerHTML='<option value="">Без категорії</option>'+cats.map(c=>`<option>${esc(c.name)}</option>`).join('')}
function renderProducts(){const q=$('#productSearch').value.trim().toLowerCase();const rows=products.filter(p=>(p.title+' '+p.product_id+' '+p.category).toLowerCase().includes(q)).slice(0,200);$('#products').innerHTML=rows.map(p=>`<label class=prod><input type=checkbox data-id="${esc(p.product_id)}" ${selected.has(p.product_id)?'checked':''}><span>${esc(p.title)}<small>${esc(p.category||'Без категорії')} · ${esc(p.product_id)}</small></span></label>`).join('');$('#products').querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id);$('#selected').textContent=selected.size+' товарів'})}
function del(i){const c=cats[i];if((c.product_count||0)>0)return alert(`Категорія не порожня: ${c.product_count} товарів. Спочатку перенесіть товари.`);if(confirm(`Видалити категорію "${c.name}"?`)){cats.splice(i,1);renderCats()}}
$('#add').onclick=()=>{syncCats();cats.push({id:'category-'+Date.now().toString(36),name:'Нова категорія',enabled:true,order:(cats.length+1)*10,parent_id:'',image:'',seo_title:'',seo_description:'',product_count:0});renderCats()};
$('#save').onclick=async()=>{syncCats();if(!confirm(`Зберегти ${cats.length} категорій і опублікувати каталог?`))return;try{const x=await api('/api/v1/admin/categories-manager',{method:'POST',body:JSON.stringify({categories:cats,publish:true})});alert(`Готово. Published: ${x.publish?.published?'YES':'NO'} · ${x.publish?.commit||''}`);load()}catch(e){alert(e.message)}};
$('#productSearch').oninput=renderProducts;
$('#move').onclick=async()=>{if(!selected.size)return alert('Не вибрано товари');const category_name=$('#moveCategory').value;if(!confirm(`Перенести ${selected.size} товарів у "${category_name||'Без категорії'}" і опублікувати?`))return;try{const x=await api('/api/v1/admin/categories-manager/move-products',{method:'POST',body:JSON.stringify({product_ids:[...selected],category_name,publish:true})});alert(`Перенесено: ${x.changed}. Published: ${x.publish?.published?'YES':'NO'}`);selected.clear();load()}catch(e){alert(e.message)}};
async function load(){try{const x=await api('/api/v1/admin/categories-manager',{headers:{Authorization:'Bearer '+token()}});cats=x.config.categories||[];products=x.products||[];localStorage.setItem('bb610_admin_token',token());renderCats();renderProducts()}catch(e){$('#categories').innerHTML='<div class=empty>Помилка: '+esc(e.message)+'</div>'}}
if(token())load();
})();