(()=>{'use strict';const API='https://api.market.bb610.com.ua';let currentDraft=null;const $=s=>document.querySelector(s);const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());loadAll()};$('#refresh').onclick=loadAll;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function dt(ts){return ts?new Date(ts*1000).toLocaleString('uk-UA'):'—'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpane').forEach(p=>p.hidden=p.id!=='tab-'+b.dataset.tab);if(b.dataset.tab==='drafts')loadDrafts();if(b.dataset.tab==='stock')loadStock();if(b.dataset.tab==='returns')loadReturns();if(b.dataset.tab==='customers')loadCustomers()});
async function loadDashboard(){const x=await api('/api/v1/admin/commerce-control');const c=x.counts||{};$('#kDrafts').textContent=c.drafts??0;$('#kReturns').textContent=c.returns_open??0;$('#kStock').textContent=c.stock_skus??0;$('#kNegative').textContent=c.negative_available??0;$('#kAlerts').textContent=c.alerts??0;$('#kCritical').textContent=c.critical_alerts??0;renderAlerts(x.alerts||[])}
function renderAlerts(a){$('#alertCount').textContent=a.length+' alerts';$('#alerts').innerHTML=a.map(x=>`<div class=alert><span class="badge ${esc(x.severity)}">${esc(x.severity)}</span><span>${esc(x.module)}</span><span class=object>${esc(x.object||'—')}</span><span>${esc(x.message)}</span></div>`).join('')||'<div class=alert>Критичних попереджень немає.</div>'}
async function loadEntities(){const type=$('#entityType').value,q=$('#entitySearch').value;const x=await api('/api/v1/admin/commerce-control/entities?entity_type='+encodeURIComponent(type)+'&q='+encodeURIComponent(q));$('#entities').innerHTML=(x.items||[]).map(i=>`<div class=entity data-id="${esc(i.id)}"><b>${esc(i.title)}</b><small>${esc(i.id)} · ${esc(i.subtitle||'')}</small></div>`).join('')||'<div class=entity>Нічого не знайдено.</div>';document.querySelectorAll('.entity[data-id]').forEach(e=>e.onclick=()=>createDraft(type,e.dataset.id))}
$('#entityType').onchange=loadEntities;$('#entitySearch').oninput=()=>{clearTimeout(window._es);window._es=setTimeout(loadEntities,250)};
async function createDraft(type,id){if(!confirm('Створити чернетку для '+id+'?'))return;try{const d=await api('/api/v1/admin/commerce-control/drafts',{method:'POST',body:JSON.stringify({entity_type:type,entity_id:id})});await loadDrafts();openDraft(d.id)}catch(e){alert(e.message)}}
async function loadDrafts(){const x=await api('/api/v1/admin/commerce-control/drafts');const arr=x.drafts||[];$('#draftCount').textContent=arr.length+' records';$('#drafts').innerHTML=arr.map(d=>`<div class=draft-card data-id="${esc(d.id)}"><b>${esc(d.entity_type)} · ${esc(d.entity_id)}</b><small>${esc(d.status)} · ${dt(d.updated_at)} · ${esc(d.note||'')}</small></div>`).join('')||'<div class=draft-card>Чернеток немає.</div>';document.querySelectorAll('.draft-card[data-id]').forEach(e=>e.onclick=()=>openDraft(e.dataset.id))}
async function openDraft(id){const d=await api('/api/v1/admin/commerce-control/drafts/'+encodeURIComponent(id));currentDraft=d;$('#editor').hidden=false;$('#editorTitle').textContent=d.entity_type+' · '+d.entity_id;$('#editorMeta').textContent='Draft '+d.id+' · '+d.status+(d.base_changed?' · SOURCE CHANGED':'');$('#draftJson').value=JSON.stringify(d.payload,null,2);$('#draftPreview').textContent=JSON.stringify(d.payload,null,2)}
$('#draftJson').oninput=()=>{$('#draftPreview').textContent=$('#draftJson').value};
$('#saveDraft').onclick=async()=>{if(!currentDraft)return;try{const payload=JSON.parse($('#draftJson').value);currentDraft=await api('/api/v1/admin/commerce-control/drafts/'+currentDraft.id,{method:'PUT',body:JSON.stringify({payload})});alert('Draft збережено');loadDrafts()}catch(e){alert(e.message)}};
$('#publishDraft').onclick=async()=>{if(!currentDraft)return;let force=false;if(currentDraft.base_changed){force=confirm('Source змінився після створення draft. Примусово опублікувати цей draft?');if(!force)return}if(!confirm('Опублікувати draft у master data та зробити git push?'))return;try{await api('/api/v1/admin/commerce-control/drafts/'+currentDraft.id+'/publish',{method:'POST',body:JSON.stringify({force,publish_git:true})});alert('Опубліковано');$('#editor').hidden=true;currentDraft=null;loadDrafts();loadDashboard()}catch(e){alert(e.message)}};
$('#discardDraft').onclick=async()=>{if(!currentDraft||!confirm('Відхилити draft?'))return;try{await api('/api/v1/admin/commerce-control/drafts/'+currentDraft.id+'/discard',{method:'POST'});$('#editor').hidden=true;currentDraft=null;loadDrafts()}catch(e){alert(e.message)}};
async function loadStock(){const q=$('#stockSearch').value;const x=await api('/api/v1/admin/commerce-control/stock?q='+encodeURIComponent(q));const rows=x.rows||[];$('#stockCount').textContent=rows.length+' SKU';$('#stockRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.sku_id)}</td><td>${esc(r.title)}</td><td class=num>${r.physical}</td><td class=num>${r.reserved}</td><td class="num ${r.available<0?'neg':'available'}">${r.available}</td><td>${esc(r.source)}</td><td><button data-stock="${esc(r.sku_id)}" data-qty="${r.physical}">Змінити</button></td></tr>`).join('')||'<tr><td colspan=7>SKU не знайдено.</td></tr>';$('#moveRows').innerHTML=(x.movements||[]).map(m=>`<tr><td>${dt(m.time)}</td><td>${esc(m.sku_id)}</td><td>${esc(m.movement_type)}</td><td>${m.qty}</td><td>${m.before_qty??'—'}</td><td>${m.after_qty??'—'}</td><td>${esc(m.note||'')}</td></tr>`).join('');document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>changeStock(b.dataset.stock,b.dataset.qty))}
$('#stockSearch').oninput=()=>{clearTimeout(window._ss);window._ss=setTimeout(loadStock,250)};
async function changeStock(sku,old){const q=prompt('Фізичний залишок для '+sku+':',old);if(q===null)return;const qty=Number(q);if(!Number.isFinite(qty)||qty<0){alert('Некоректне значення');return}const note=prompt('Причина корекції:','Manual correction')||'Manual correction';try{await api('/api/v1/admin/commerce-control/stock/set',{method:'POST',body:JSON.stringify({sku_id:sku,qty,note})});loadStock();loadDashboard()}catch(e){alert(e.message)}}
$('#syncStock').onclick=async()=>{if(!confirm('Перезаписати physical stock значеннями з поточного catalog commerce?'))return;try{const x=await api('/api/v1/admin/commerce-control/stock/sync',{method:'POST'});alert(`Sync: added ${x.added}, updated ${x.updated}`);loadStock()}catch(e){alert(e.message)}};
$('#rebuildReservations').onclick=async()=>{if(!confirm('Перебудувати резерви за відкритими замовленнями?'))return;try{const x=await api('/api/v1/admin/commerce-control/reservations/rebuild',{method:'POST'});alert(`Orders found: ${x.orders_found}. Reservations: ${x.reservations}. Unresolved: ${(x.unresolved_orders||[]).length}`);loadStock();loadDashboard()}catch(e){alert(e.message)}};
function parseItems(){return $('#retItems').value.split(/\n+/).map(s=>s.trim()).filter(Boolean).map(line=>{const [sku,qty]=line.split(',');return {sku_id:(sku||'').trim(),qty:Number(qty||1)}}).filter(x=>x.sku_id&&Number.isFinite(x.qty)&&x.qty>0)}
$('#createReturn').onclick=async()=>{const body={order_id:$('#retOrder').value.trim(),items:parseItems(),reason:$('#retReason').value.trim(),refund_amount:Number($('#retAmount').value||0),restock:$('#retRestock').checked};if(!body.order_id||!body.items.length){alert('Потрібні Order ID та items');return}try{const x=await api('/api/v1/admin/commerce-control/returns',{method:'POST',body:JSON.stringify(body)});alert('Створено '+x.return_id);$('#retOrder').value='';$('#retItems').value='';loadReturns();loadDashboard()}catch(e){alert(e.message)}};
async function loadReturns(){const x=await api('/api/v1/admin/commerce-control/returns');const arr=x.returns||[];$('#returnCount').textContent=arr.length+' returns';$('#returns').innerHTML=arr.map(r=>`<div class=return-card><div class=top><div><b>${esc(r.id)}</b><small>Order ${esc(r.order_id)} · ${dt(r.created_at)} · refund ${r.refund_amount}</small></div><select data-return="${esc(r.id)}">${['requested','approved','received','refunded','completed','rejected'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></div><small>${esc(r.reason||'')} · restock ${r.restock?'YES':'NO'}</small><small>${(r.items||[]).map(i=>esc(i.sku_id)+' × '+i.qty).join(', ')}</small></div>`).join('')||'<div class=return-card>Повернень немає.</div>';document.querySelectorAll('[data-return]').forEach(s=>s.onchange=()=>setReturn(s.dataset.return,s.value))}
async function setReturn(id,status){if(status==='completed'&&!confirm('Завершити return? Якщо restock=YES, кількість буде додана у physical stock.')){loadReturns();return}try{await api('/api/v1/admin/commerce-control/returns/'+encodeURIComponent(id)+'/status',{method:'POST',body:JSON.stringify({status})});loadReturns();loadStock();loadDashboard()}catch(e){alert(e.message);loadReturns()}}
async function loadCustomers(){const q=$('#customerSearch').value;const x=await api('/api/v1/admin/commerce-control/customers?q='+encodeURIComponent(q));const arr=x.customers||[];$('#customerCount').textContent=arr.length+' customers';$('#customers').innerHTML=arr.map(c=>`<div class=customer><b>${esc(c.name||c.customer_key)}</b><small>${esc(c.phone||'')} · ${esc(c.email||'')}</small><div class=stats><span>${c.order_count} orders</span><span>${c.total_amount.toFixed(2)} грн</span></div><small>${(c.orders||[]).slice(0,5).map(o=>esc(o.order_id)+' · '+esc(o.status)+' · '+o.amount).join('<br>')}</small><div class=notes>${(c.notes||[]).slice(0,3).map(n=>`<small>${dt(n.created_at)} — ${esc(n.note)}</small>`).join('')}<textarea data-note="${esc(c.customer_key)}" placeholder="Нова нотатка"></textarea><button data-addnote="${esc(c.customer_key)}">Додати нотатку</button></div></div>`).join('')||'<div class=customer>Клієнтів не знайдено.</div>';document.querySelectorAll('[data-addnote]').forEach(b=>b.onclick=()=>addNote(b.dataset.addnote))}
$('#customerSearch').oninput=()=>{clearTimeout(window._cs);window._cs=setTimeout(loadCustomers,250)};
async function addNote(key){const ta=document.querySelector(`textarea[data-note="${CSS.escape(key)}"]`),note=ta?.value.trim();if(!note)return;try{await api('/api/v1/admin/commerce-control/customers/note',{method:'POST',body:JSON.stringify({customer_key:key,note})});loadCustomers()}catch(e){alert(e.message)}}
async function loadAll(){try{localStorage.setItem('bb610_admin_token',token());await loadDashboard();loadEntities()}catch(e){alert(e.message)}}
if(token())loadAll();})();