(()=>{
 const cfg=window.BB610_ADMIN_CONFIG||{},base=(cfg.apiBaseUrl||'').replace(/\/$/,''),ep='/api/v1/admin/integrations/nova-poshta';
 const $=id=>document.getElementById(id),token=$('token'); token.value=sessionStorage.getItem('bb610_admin_token')||'';
 const H=()=>({'Authorization':'Bearer '+token.value.trim(),'Content-Type':'application/json','Accept':'application/json'});
 async function req(path,opt={}){if(!/^https?:\/\//.test(base))throw new Error('Не налаштовано API URL адмінки');const c=new AbortController(),t=setTimeout(()=>c.abort(),cfg.requestTimeoutMs||12000);try{const r=await fetch(base+path,{...opt,signal:c.signal,headers:{...H(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
 function paint(s){$('key-state').textContent=s.api_key?.configured?'Налаштовано':'Не налаштовано';$('key-state').className=s.api_key?.configured?'ok':'warn';$('key-source').textContent=s.api_key?.configured?`Джерело: ${s.api_key.source==='secure_store'?'захищене сховище':'поточний .env'}`:'';$('lookup-state').textContent=s.configured?'Готово':'Недоступно';$('lookup-state').className=s.configured?'ok':'warn';$('shipment-state').textContent=s.shipment_ready?'Готово':'Ще не готово';$('shipment-state').className=s.shipment_ready?'ok':'warn';$('api-url').value=s.api_url||'https://api.novaposhta.ua/v2.0/json/';$('sender-ref').value=s.sender?.sender_ref||'';$('sender-contact-ref').value=s.sender?.sender_contact_ref||'';$('sender-address-ref').value=s.sender?.sender_address_ref||'';$('np-status').textContent=s.configured?'Підключено':'Не підключено';$('np-status').className='badge '+(s.configured?'live':'draft')}
 async function load(){sessionStorage.setItem('bb610_admin_token',token.value.trim());$('state').textContent='Завантаження…';const s=await req(ep);paint(s);$('state').textContent=''}
 async function save(){const body={api_url:$('api-url').value.trim(),sender_ref:$('sender-ref').value.trim(),sender_contact_ref:$('sender-contact-ref').value.trim(),sender_address_ref:$('sender-address-ref').value.trim()};const k=$('api-key').value.trim();if(k)body.api_key=k;$('state').textContent='Збереження…';const s=await req(ep,{method:'PATCH',body:JSON.stringify(body)});$('api-key').value='';paint(s);$('state').textContent='✓ Збережено'}
 async function test(){const b=$('test');b.disabled=true;$('state').textContent='Перевірка Nova Poshta…';try{const r=await req(ep+'/test',{method:'POST',body:'{}'});$('state').textContent=`✓ Підключення працює · знайдено ${r.results} результатів`;$('np-status').textContent='Підключено';$('np-status').className='badge live'}catch(e){$('state').textContent='✕ '+e.message;$('np-status').textContent='Помилка';$('np-status').className='badge draft'}finally{b.disabled=false}}
 $('connect').onclick=()=>load().catch(e=>$('state').textContent='✕ '+e.message);$('save').onclick=()=>save().catch(e=>$('state').textContent='✕ '+e.message);$('test').onclick=test;$('toggle-key').onclick=()=>{const x=$('api-key');x.type=x.type==='password'?'text':'password';$('toggle-key').textContent=x.type==='password'?'Показати при вводі':'Сховати'};if(token.value)load().catch(e=>$('state').textContent='✕ '+e.message)
})();
