(()=>{
 const cfg=window.BB610_ADMIN_CONFIG||{},base=(cfg.apiBaseUrl||'').replace(/\/$/,''),ep='/api/v1/admin/integrations/nova-poshta',payEp='/api/v1/admin/integrations/payments',$=id=>document.getElementById(id),token=$('token');token.value=sessionStorage.getItem('bb610_admin_token')||'';
 const H=()=>({'Authorization':'Bearer '+token.value.trim(),'Content-Type':'application/json','Accept':'application/json'});
 async function req(path,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),cfg.requestTimeoutMs||12000);try{const r=await fetch(base+path,{...opt,signal:c.signal,headers:{...H(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
 const mark=(id,ok,yes='Готово',no='Не готово')=>{const e=$(id);e.textContent=ok?yes:no;e.className=ok?'ok':'warn'};
 function paint(s){mark('api-state',s.api_ready,'Доступний','Недоступний');mark('checkout-state',s.checkout_ready,'Готово','Не підключено');mark('cod-state',s.cod_ready,'Готово','Не активовано');mark('shipment-state',s.shipment_ready,'Готово','Не налаштовано');$('shipment-note').textContent=s.shipment_ready?'ТТН створюється з картки замовлення.':'Оберіть відправника, контакт і адресу.';$('key-source').textContent=s.api_key?.configured?`Ключ: ${s.api_key.source==='secure_store'?'захищене сховище':'поточний .env'}`:'';$('api-url').value=s.api_url||'https://api.novaposhta.ua/v2.0/json/';$('np-status').textContent=s.configured?'Підключено':'Не підключено';$('np-status').className='badge '+(s.configured?'live':'draft');$('sender-select').dataset.current=s.sender?.sender_ref||'';$('contact-select').dataset.current=s.sender?.sender_contact_ref||'';$('address-select').dataset.current=s.sender?.sender_address_ref||'';const sh=s.shipping||{};$('shipment-weight').value=sh.weight||'1.0';$('shipment-description').value=sh.description||'Товари для вирощування';$('payer-type').value=sh.payer_type||'Recipient';$('payment-method').value=sh.payment_method||'Cash'}
 async function load(){sessionStorage.setItem('bb610_admin_token',token.value.trim());$('state').textContent='Завантаження…';const [s,p]=await Promise.all([req(ep),req(payEp)]);paint(s);paintPayments(p);$('state').textContent=''}
 
 function paintPayments(p){const cod=!!p.cod?.enabled,bank=!!p.bank_transfer?.ready,bankEnabled=!!p.bank_transfer?.enabled,card=!!p.online_card?.enabled;mark('pay-cod-state',cod,'Активна','Вимкнена');mark('pay-bank-state',bank,'Готова',bankEnabled?'Не завершено':'Вимкнена');$('pay-bank-note').textContent=bank?'Реквізити заповнені.':(bankEnabled?'Заповніть отримувача та IBAN.':'');mark('pay-card-state',card,card?(p.online_card?.provider||'Активна'):'Stage 14B','Stage 14B');$('pay-status').textContent=(cod||bank||card)?'Налаштовано':'Не налаштовано';$('pay-status').className='badge '+((cod||bank||card)?'live':'draft');$('pay-cod-enabled').checked=cod;$('pay-bank-enabled').checked=bankEnabled;$('pay-bank-recipient').value=p.bank_transfer?.recipient||'';$('pay-bank-iban').value=p.bank_transfer?.iban||'';$('pay-bank-purpose').value=p.bank_transfer?.purpose||'Оплата замовлення {order_number}' }
 async function savePayments(){const body={cod_enabled:$('pay-cod-enabled').checked,bank_transfer_enabled:$('pay-bank-enabled').checked,bank_recipient:$('pay-bank-recipient').value.trim(),bank_iban:$('pay-bank-iban').value.trim(),bank_purpose:$('pay-bank-purpose').value.trim()};$('pay-state').textContent='Збереження…';const p=await req(payEp,{method:'PATCH',body:JSON.stringify(body)});paintPayments(p);$('pay-state').textContent='✓ Збережено'}

 async function loadSenderOptions(){const b=$('load-senders');b.disabled=true;$('state').textContent='Завантаження відправників…';try{const d=await req(ep+'/senders');const cur=$('sender-select').dataset.current||'';$('sender-select').innerHTML='<option value="">Оберіть відправника</option>'+(d.senders||[]).map(x=>`<option value="${x.ref}" ${x.ref===cur?'selected':''}>${x.label||x.ref}${x.city?' · '+x.city:''}</option>`).join('');if($('sender-select').value)await loadDependent($('sender-select').value);$('state').textContent=`✓ Відправників: ${(d.senders||[]).length}`}catch(e){$('state').textContent='✕ '+e.message}finally{b.disabled=false}}
 async function loadDependent(ref){$('contact-select').disabled=true;$('address-select').disabled=true;const d=await req(ep+'/sender-options?sender_ref='+encodeURIComponent(ref));const cc=$('contact-select').dataset.current||'',ac=$('address-select').dataset.current||'';$('contact-select').innerHTML='<option value="">Оберіть контакт</option>'+(d.contacts||[]).map(x=>`<option value="${x.ref}" ${x.ref===cc?'selected':''}>${x.label||x.ref}${x.phone?' · '+x.phone:''}</option>`).join('');$('address-select').innerHTML='<option value="">Оберіть адресу</option>'+(d.addresses||[]).map(x=>`<option value="${x.ref}" ${x.ref===ac?'selected':''}>${x.label||x.ref}${x.city?' · '+x.city:''}</option>`).join('');$('contact-select').disabled=false;$('address-select').disabled=false}
 async function save(){const body={api_url:$('api-url').value.trim(),sender_ref:$('sender-select').value,sender_contact_ref:$('contact-select').value,sender_address_ref:$('address-select').value,shipment_weight:Number($('shipment-weight').value||1),shipment_description:$('shipment-description').value.trim(),payer_type:$('payer-type').value,payment_method:$('payment-method').value};const k=$('api-key').value.trim();if(k)body.api_key=k;$('state').textContent='Збереження…';const s=await req(ep,{method:'PATCH',body:JSON.stringify(body)});$('api-key').value='';paint(s);$('state').textContent='✓ Збережено'}
 async function test(){const b=$('test');b.disabled=true;$('state').textContent='Перевірка Nova Poshta…';try{const r=await req(ep+'/test',{method:'POST',body:'{}'});$('state').textContent=`✓ API працює · знайдено ${r.results} результатів`;await load()}catch(e){$('state').textContent='✕ '+e.message}finally{b.disabled=false}}
 $('connect').onclick=()=>load().catch(e=>$('state').textContent='✕ '+e.message);$('pay-save').onclick=()=>savePayments().catch(e=>$('pay-state').textContent='✕ '+e.message);$('save').onclick=()=>save().catch(e=>$('state').textContent='✕ '+e.message);$('test').onclick=test;$('load-senders').onclick=loadSenderOptions;$('sender-select').onchange=()=>{if($('sender-select').value)loadDependent($('sender-select').value).catch(e=>$('state').textContent='✕ '+e.message)};$('toggle-key').onclick=()=>{const x=$('api-key');x.type=x.type==='password'?'text':'password'};if(token.value)load().catch(e=>$('state').textContent='✕ '+e.message)
})();
