(()=>{'use strict';const API='https://api.market.bb610.com.ua';let orders=[],labels={},chain=[],active=null;const $=s=>document.querySelector(s);const token=()=>$('#token').value.trim();const hdr=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',token());load()};$('#refresh').onclick=load;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...hdr(),...(opt.headers||{})}}),x=await r.json().catch(()=>({detail:'Unknown error'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
function money(v){return v==null||v===''?'—':new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(Number(v))+' грн'}function fmtDate(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('uk-UA')}
function badge(s){const c=s==='cancelled'?'red':s==='completed'?'ok':s==='new'?'warn':'off';return `<span class="badge ${c}">${esc(labels[s]||s)}</span>`}
function renderQueues(counts){const all=[...chain,'cancelled'];$('#queues').innerHTML=all.map(s=>`<div class=queue data-s="${s}"><b>${counts[s]||0}</b><span>${esc(labels[s]||s)}</span></div>`).join('');document.querySelectorAll('.queue').forEach(q=>q.onclick=()=>{$('#status').value=q.dataset.s;render()})}
function render(){const q=$('#search').value.trim().toLowerCase(),st=$('#status').value,del=$('#delivery').value;const list=orders.filter(o=>{const hay=(o.id+' '+o.customer_name+' '+o.phone+' '+o.email+' '+o.ttn+' '+o.city+' '+o.branch).toLowerCase();if(q&&!hay.includes(q))return false;if(st&&o.status!==st)return false;if(del&&o.delivery_method!==del)return false;return true});$('#count').textContent=list.length+' замовлень';$('#rows').innerHTML=list.map(o=>`<tr data-id="${esc(o.id)}" class="${active===o.id?'active':''}"><td><b>${esc(o.id)}</b></td><td>${fmtDate(o.created_at)}</td><td>${esc(o.customer_name||'—')}<br><small>${esc(o.phone||'')}</small></td><td>${badge(o.status)}</td><td>${esc(o.payment_method||'—')}<br><small>${esc(o.payment_status||'')}</small></td><td>${esc(o.delivery_method||'—')}<br><small>${esc(o.ttn||'')}</small></td><td>${money(o.total)}</td></tr>`).join('')||'<tr><td colspan=7>Нічого не знайдено.</td></tr>';document.querySelectorAll('tbody tr[data-id]').forEach(r=>r.onclick=()=>{active=r.dataset.id;detail(active);render()})}
async function detail(id){try{const x=await api('/api/v1/admin/order-center/'+encodeURIComponent(id));const o=x.order,i=chain.indexOf(o.status),canBack=o.status!=='cancelled'&&i>0,canForward=o.status!=='cancelled'&&i>=0&&i<chain.length-1;$('#detail').innerHTML=`<h2>Замовлення №${esc(o.id)}</h2><div class=meta>${fmtDate(o.created_at)} · ${badge(o.status)}</div><div class=detail-grid><div><small>Клієнт</small>${esc(o.customer_name||'—')}</div><div><small>Телефон</small>${esc(o.phone||'—')}</div><div><small>Email</small>${esc(o.email||'—')}</div><div><small>Сума</small>${money(o.total)}</div><div><small>Оплата</small>${esc(o.payment_method||'—')}<br>${esc(o.payment_status||'')}</div><div><small>Доставка</small>${esc(o.delivery_method||'—')}</div><div><small>Місто</small>${esc(o.city||'—')}</div><div><small>Відділення</small>${esc(o.branch||'—')}</div><div><small>ТТН</small>${esc(o.ttn||'Ще немає')}</div><div><small>Коментар клієнта</small>${esc(o.comment||'—')}</div></div><div class=actions><button id=back ${canBack?'':'disabled'}>← Попередній статус</button><button id=forward ${canForward?'':'disabled'}>Наступний статус →</button><button id=cancel class=cancel ${o.status==='cancelled'?'disabled':''}>Скасувати замовлення</button></div><div class=note><input id=noteText placeholder="Коментар менеджера"><button id=addNote>Додати</button></div><div class=history><h3>Історія</h3>${[...(o.events||[]),...(o.notes||[]).map(n=>({event_type:'note',reason:n.note,created_at:n.created_at}))].sort((a,b)=>(b.created_at||0)-(a.created_at||0)).map(e=>`<div class=event><b>${esc(e.event_type)}</b>${e.from_status||e.to_status?` · ${esc(labels[e.from_status]||e.from_status||'')} → ${esc(labels[e.to_status]||e.to_status||'')}`:''}<small>${esc(e.reason||'')} · ${e.created_at?new Date(e.created_at*1000).toLocaleString('uk-UA'):''}</small></div>`).join('')||'<div class=empty>Історія порожня.</div>'}</div>`;$('#back').onclick=()=>move(id,'back');$('#forward').onclick=()=>move(id,'forward');$('#cancel').onclick=()=>cancelOrder(id);$('#addNote').onclick=()=>note(id)}catch(e){$('#detail').innerHTML='<div class=empty>'+esc(e.message)+'</div>'}}
async function move(id,direction){if(!confirm(direction==='forward'?'Перевести замовлення на наступний статус?':'Відкотити замовлення лише на один статус назад?'))return;try{await api('/api/v1/admin/order-center/transition',{method:'POST',body:JSON.stringify({order_id:id,direction})});await load();active=id;detail(id)}catch(e){alert(e.message)}}
async function cancelOrder(id){if(!confirm('Скасувати замовлення? Повернення зі статусу "Скасовано" не передбачено.'))return;const reason=prompt('Причина скасування (необов’язково):','');if(reason===null)return;try{await api('/api/v1/admin/order-center/cancel',{method:'POST',body:JSON.stringify({order_id:id,reason})});await load();active=id;detail(id)}catch(e){alert(e.message)}}
async function note(id){const n=$('#noteText').value.trim();if(!n)return;try{await api('/api/v1/admin/order-center/note',{method:'POST',body:JSON.stringify({order_id:id,note:n})});detail(id)}catch(e){alert(e.message)}}
['search','status','delivery'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));
async function load(){try{const x=await api('/api/v1/admin/order-center',{headers:{Authorization:'Bearer '+token()}});orders=x.orders||[];labels=x.status_labels||{};chain=x.status_chain||[];$('#source').textContent='Джерело: '+x.source;$('#status').innerHTML='<option value="">Усі статуси</option>'+[...chain,'cancelled'].map(s=>`<option value="${s}">${esc(labels[s]||s)}</option>`).join('');const dels=[...new Set(orders.map(o=>o.delivery_method).filter(Boolean))].sort();$('#delivery').innerHTML='<option value="">Усі доставки</option>'+dels.map(d=>`<option>${esc(d)}</option>`).join('');renderQueues(x.counts||{});localStorage.setItem('bb610_admin_token',token());render();if(active)detail(active)}catch(e){$('#rows').innerHTML='<tr><td colspan=7>'+esc(e.message)+'</td></tr>'}}
if(token())load();})();