
(()=>{'use strict';const API='https://api.market.bb610.com.ua';const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const token=()=>$('#token').value||localStorage.getItem('bb610_admin_token')||'';let cards=[],current=null;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json',...(opt.headers||{})}});const x=await r.json().catch(()=>({detail:'Помилка'}));if(!r.ok)throw new Error(x.detail||JSON.stringify(x));return x}
$('#token').value=localStorage.getItem('bb610_admin_token')||'';$('#connect').onclick=()=>{localStorage.setItem('bb610_admin_token',$('#token').value);load()};$('#search').oninput=renderList;$('#state').onchange=renderList;$('#new').onclick=()=>edit({name:'',official_name:'',brand:'',category_id:'',slug:'',id:'',short_description:'',description:'',image:{local:''},gallery:[],cultures:[],purposes:[],default_sku_id:'',launch_sku_ids:[],feed_policy:'allowed',status:'draft'},true);
async function load(){const x=await api('/api/v1/admin/product-cards');cards=x.items||[];renderList()}
function renderList(){const q=$('#search').value.toLowerCase(),st=$('#state').value;$('#list').innerHTML=cards.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!st||(st==='archived'?x.archived:!x.archived))).map(x=>`<div class="pc-item" data-id="${esc(x.id||x.slug)}"><img src="/${esc(x.image||'assets/img/placeholder.svg')}"><div><b>${esc(x.name)}</b><small>${esc(x.brand)} · ${esc(x.category)}</small><small>${esc((x.skus||[]).join(', '))}</small></div></div>`).join('');document.querySelectorAll('.pc-item').forEach(el=>el.onclick=()=>open(el.dataset.id))}
async function open(id){current=await api('/api/v1/admin/product-cards/'+encodeURIComponent(id));edit(current,false)}
function vals(a){return (a||[]).join('\n')}
function edit(c,isNew){current=c;$('#editor').innerHTML=`<div class=tabs><div class="tab active" data-t=main>Основне</div><div class=tab data-t=text>Опис</div><div class=tab data-t=media>Фото</div><div class=tab data-t=sku>SKU</div><div class=tab data-t=use>Застосування</div></div><div class="pane active" data-p=main><div class=grid2><label class=field>Назва<input id=f_name value="${esc(c.name||'')}"></label><label class=field>Бренд<input id=f_brand value="${esc(c.brand||'')}"></label><label class=field>Категорія<input id=f_category value="${esc(c.category_id||c.category||'')}"></label><label class=field>Feed policy<select id=f_feed><option ${c.feed_policy==='allowed'?'selected':''}>allowed</option><option ${c.feed_policy==='review-required'?'selected':''}>review-required</option><option ${c.feed_policy==='blocked'?'selected':''}>blocked</option></select></label><label class=field>Slug<input id=f_slug value="${esc(c.slug||'')}"></label><label class=field>ID<input id=f_id value="${esc(c.id||'')}"></label></div></div><div class=pane data-p=text><label class=field>Короткий опис<textarea id=f_short>${esc(c.short_description||'')}</textarea></label><label class=field>Повний опис<textarea id=f_desc>${esc(c.description||'')}</textarea></label></div><div class=pane data-p=media><label class=field>Головне фото<input id=f_image value="${esc(c.image?.local||'')}"></label><img class=preview id=preview src="/${esc(c.image?.local||'assets/img/placeholder.svg')}"><label class=field>Галерея — один шлях на рядок<textarea id=f_gallery>${esc(vals(c.gallery))}</textarea></label></div><div class=pane data-p=sku><label class=field>Основний SKU<input id=f_default value="${esc(c.default_sku_id||'')}"></label><label class=field>Усі SKU — один на рядок<textarea id=f_skus>${esc(vals(c.launch_sku_ids))}</textarea></label></div><div class=pane data-p=use><label class=field>Культури — один пункт на рядок<textarea id=f_cultures>${esc(vals(c.cultures))}</textarea></label><label class=field>Застосування / призначення<textarea id=f_purposes>${esc(vals(c.purposes))}</textarea></label></div><div class=actions><button class=primary id=save>${isNew?'Створити товар':'Зберегти картку'}</button>${isNew?'':`<button id=duplicate>Дублювати</button><button id=archive>В архів</button><button class=danger id=delete>Видалити</button>`}</div>`;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelector(`[data-p="${t.dataset.t}"]`).classList.add('active')});$('#f_image').oninput=()=>$('#preview').src='/'+$('#f_image').value;$('#save').onclick=()=>save(isNew);if(!isNew){$('#duplicate').onclick=duplicate;$('#archive').onclick=archive;$('#delete').onclick=del}}
function collect(){const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);return {...current,name:$('#f_name').value.trim(),brand:$('#f_brand').value.trim(),category_id:$('#f_category').value.trim(),feed_policy:$('#f_feed').value,slug:$('#f_slug').value.trim(),id:$('#f_id').value.trim(),short_description:$('#f_short').value.trim(),description:$('#f_desc').value.trim(),image:{...(current.image||{}),local:$('#f_image').value.trim()},gallery:lines('#f_gallery'),default_sku_id:$('#f_default').value.trim(),launch_sku_ids:lines('#f_skus'),cultures:lines('#f_cultures'),purposes:lines('#f_purposes')}}
async function save(isNew){try{const card=collect();const x=await api(isNew?'/api/v1/admin/product-cards':'/api/v1/admin/product-cards/'+encodeURIComponent(current.id||current.slug),{method:isNew?'POST':'PUT',body:JSON.stringify({card})});alert('Збережено');await load();await open(x.id||x.slug)}catch(e){alert(e.message)}}
async function duplicate(){if(!confirm('Створити копію картки без SKU?'))return;try{const x=await api('/api/v1/admin/product-cards/'+encodeURIComponent(current.id||current.slug)+'/duplicate',{method:'POST'});await load();await open(x.id||x.slug)}catch(e){alert(e.message)}}
async function archive(){if(!confirm('Перемістити товар в архів?'))return;try{await api('/api/v1/admin/product-cards/'+encodeURIComponent(current.id||current.slug)+'/archive',{method:'POST'});await load();$('#editor').innerHTML='<div class=empty>Товар архівовано.</div>'}catch(e){alert(e.message)}}
async function del(){if(!confirm('Видалити товар? Якщо є посилання/історія, система замість видалення архівує його.'))return;try{const x=await api('/api/v1/admin/product-cards/'+encodeURIComponent(current.id||current.slug),{method:'DELETE'});alert(x.deleted?'Товар видалено':'Є зв’язки — товар архівовано');await load();$('#editor').innerHTML='<div class=empty>Готово.</div>'}catch(e){alert(e.message)}}
if($('#token').value)load();
})();